import json
import os
import re

DATA_PATH = 'src/data/grades/grade10.js'

with open(DATA_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

json_match = re.search(r'export\s+const\s+\w+\s*=\s*(\{[\s\S]*\});?\s*$', content)
if not json_match:
    raise ValueError("Could not extract grade10Data object")

grade10Data = json.loads(json_match.group(1))

def make_q(q_id, difficulty, question, options_list, correct_key, hint, best_solution):
    return {
        "id": q_id,
        "category": "Latihan",
        "difficulty": difficulty,
        "question": question,
        "options": [
            {"key": "A", "text": options_list[0]},
            {"key": "B", "text": options_list[1]},
            {"key": "C", "text": options_list[2]},
            {"key": "D", "text": options_list[3]}
        ],
        "correctAnswer": correct_key,
        "hint": hint,
        "bestSolution": best_solution
    }

# =========================================================================
# BAB 1: Eksponen & Logaritma (16 questions)
# =========================================================================
b1_add = [
    make_q("sma10-b1-5", "Dasar", "Nilai dari operasi logaritma $^2\\log 32 - ^2\\log 4$ adalah...", ["3", "4", "2", "5"], "A", "Gunakan sifat: $^a\\log b - ^a\\log c = ^a\\log (b/c)$.", "**Langkah Penyelesaian Terstruktur:**\\n$$^2\\log 32 - ^2\\log 4 = ^2\\log \\left(\\frac{32}{4}\\right) = ^2\\log 8 = 3$$\\nNilainya adalah **3** (Opsi A)."),
    make_q("sma10-b1-6", "Sedang", "Bentuk sederhana dari $\\frac{(x^2 y^{-3})^2}{x^{-1} y^2}$ adalah...", ["\\frac{x^5}{y^8}", "\\frac{x^3}{y^8}", "x^5 y^4", "\\frac{x^4}{y^6}"], "A", "Pangkatkan pembilang $(x^2)^2 y^{-6} = x^4 y^{-6}$, lalu kurangkan eksponen penyebut.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{x^4 y^{-6}}{x^{-1} y^2} = x^{4 - (-1)} y^{-6 - 2} = x^5 y^{-8} = \\frac{x^5}{y^8}$$ (Opsi A)."),
    make_q("sma10-b1-7", "Sedang", "Himpunan penyelesaian dari persamaan eksponen $2^{3x - 1} = 32$ adalah...", ["{2}", "{3}", "{1}", "{\\frac{5}{3}}"], "A", "Ubah 32 menjadi $2^5$, lalu samakan eksponennya.", "**Langkah Penyelesaian Terstruktur:**\\n$$2^{3x - 1} = 2^5 \\implies 3x - 1 = 5 \\implies 3x = 6 \\implies x = 2$$ (Opsi A)."),
    make_q("sma10-b1-8", "Sedang", "Jika $^3\\log 2 = a$, maka nilai dari $^3\\log 12$ dinyatakan dalam $a$ adalah...", ["2a + 1", "a + 2", "2a + 2", "a + 1"], "A", "Faktorkan $12 = 2^2 \\times 3$. Gunakan sifat penjumlahan logaritma.", "**Langkah Penyelesaian Terstruktur:**\\n$$^3\\log 12 = ^3\\log (2^2 \\times 3) = 2(^3\\log 2) + ^3\\log 3 = 2a + 1$$ (Opsi A)."),
    make_q("sma10-b1-9", "Sedang", "Nilai dari operasi $^2\\log 3 \\cdot ^3\\log 5 \\cdot ^5\\log 8$ adalah...", ["3", "2", "4", "1"], "A", "Gunakan sifat perkalian berantai logaritma: $^a\\log b \\cdot ^b\\log c = ^a\\log c$.", "**Langkah Penyelesaian Terstruktur:**\\n$$^2\\log 3 \\cdot ^3\\log 5 \\cdot ^5\\log 8 = ^2\\log 8 = 3$$ (Opsi A)."),
    make_q("sma10-b1-10", "Sedang", "Bentuk rasional dari $\\frac{6}{\\sqrt{7} - 2}$ adalah...", ["2\\sqrt{7} + 4", "2\\sqrt{7} - 4", "\\sqrt{7} + 2", "3\\sqrt{7} + 6"], "A", "Kalikan dengan sekawan: $\\frac{\\sqrt{7} + 2}{\\sqrt{7} + 2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{6(\\sqrt{7} + 2)}{7 - 4} = \\frac{6(\\sqrt{7} + 2)}{3} = 2\\sqrt{7} + 4$$ (Opsi A)."),
    make_q("sma10-b1-11", "Sedang", "Penyelesaian dari persamaan eksponen $5^{x^2 - 3x - 4} = 1$ adalah...", ["x = 4 atau x = -1", "x = 4 atau x = 1", "x = -4 atau x = 1", "x = 2 atau x = -2"], "A", "Eksponen harus sama dengan nol karena $5^0 = 1$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x^2 - 3x - 4 = 0 \\implies (x - 4)(x + 1) = 0 \\implies x = 4 \\text{ atau } x = -1$$ (Opsi A)."),
    make_q("sma10-b1-12", "Sedang", "Suatu modal sebesar Rp10.000.000,00 diinvestasikan dengan bunga majemuk $10\\%$ per tahun. Besar modal pada akhir tahun ke-3 adalah...", ["Rp13.310.000,00", "Rp13.000.000,00", "Rp12.100.000,00", "Rp14.000.000,00"], "A", "Rumus bunga majemuk: $M_3 = M_0 (1 + i)^3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$M_3 = 10.000.000 \\times (1{,}1)^3 = 10.000.000 \\times 1{,}331 = \\text{Rp}13.310.000,00$$ (Opsi A)."),
    make_q("sma10-b1-13", "Sedang", "Massa zat radioaktif mula-mula 160 gram dan meluruh menjadi setengahnya setiap 4 jam. Sisa massa zat setelah 16 jam adalah...", ["10 gram", "20 gram", "5 gram", "15 gram"], "A", "Periode $n = 16 / 4 = 4$. Rumus: $M = 160 \\times (1/2)^4$.", "**Langkah Penyelesaian Terstruktur:**\\n$$M = 160 \\times \\left(\\frac{1}{2}\\right)^4 = 160 \\times \\frac{1}{16} = 10\\text{ gram}$$ (Opsi A)."),
    make_q("sma10-b1-14", "Sedang", "Jika $\\log 2 = 0{,}3010$ dan $\\log 3 = 0{,}4771$, maka nilai dari $\\log 18$ adalah...", ["1,2552", "1,2792", "1,1542", "1,3012"], "A", "$\\log 18 = \\log (2 \\times 3^2) = \\log 2 + 2\\log 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\log 18 = 0{,}3010 + 2(0{,}4771) = 0{,}3010 + 0{,}9542 = 1{,}2552$$ (Opsi A)."),
    make_q("sma10-b1-15", "Sedang", "Himpunan penyelesaian dari $\\log(x + 6) + \\log(x - 3) = 1$ dengan basis 10 adalah...", ["{4}", "{4, -7}", "{5}", "{-7}"], "A", "Gabungkan logaritma: $(x+6)(x-3) = 10$. Periksa syarat numerus $x > 3$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $x^2 + 3x - 18 = 10 \\implies x^2 + 3x - 28 = 0 \\implies (x + 7)(x - 4) = 0$\\n2. Syarat numerus: $x > 3$, sehingga yang memenuhi hanya $x = 4$ (Opsi A)."),
    make_q("sma10-b1-16", "Tantangan", "Nilai $x$ yang memenuhi persamaan eksponen $9^x - 4 \\cdot 3^{x+1} + 27 = 0$ adalah...", ["x = 1 atau x = 2", "x = 0 atau x = 3", "x = 1 atau x = 3", "x = 2 atau x = 3"], "A", "Misalkan $y = 3^x$, persamaan menjadi $y^2 - 12y + 27 = 0$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $(y - 3)(y - 9) = 0 \\implies y = 3$ atau $y = 9$\\n2. $3^x = 3 \\implies x = 1$ dan $3^x = 9 \\implies x = 2$ (Opsi A)."),
    make_q("sma10-b1-17", "Tantangan", "Jika $^2\\log 3 = a$ dan $^3\\log 5 = b$, maka nilai dari $^{15}\\log 20$ adalah...", ["\\frac{2 + ab}{a(1 + b)}", "\\frac{2a + b}{1 + ab}", "\\frac{a + 2b}{a(1 + b)}", "\\frac{2 + a}{a + b}"], "A", "Ubah basis ke 3: $^{15}\\log 20 = \\frac{^3\\log 20}{^3\\log 15}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$^{15}\\log 20 = \\frac{2(^3\\log 2) + ^3\\log 5}{^3\\log 3 + ^3\\log 5} = \\frac{\\frac{2}{a} + b}{1 + b} = \\frac{2 + ab}{a(1 + b)}$$ (Opsi A)."),
    make_q("sma10-b1-18", "Tantangan", "Penyelesaian dari pertidaksamaan eksponen $\\left(\\frac{1}{3}\\right)^{2x - 1} \\le 27$ adalah...", ["x \\ge -1", "x \\le -1", "x \\ge 2", "x \\le 2"], "A", "Ubah ke basis 3: $3^{-(2x - 1)} \\le 3^3 \\implies -2x + 1 \\le 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$-2x + 1 \\le 3 \\implies -2x \\le 2 \\implies x \\ge -1$$ (Opsi A)."),
    make_q("sma10-b1-19", "Tantangan", "Himpunan penyelesaian dari pertidaksamaan logaritma $^2\\log(x - 2) < 3$ adalah...", ["2 < x < 10", "x < 10", "x > 2", "2 < x < 8"], "A", "Selesaikan $x - 2 < 2^3 = 8$ dengan syarat numerus $x - 2 > 0$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $x - 2 < 8 \\implies x < 10$\\n2. Syarat numerus: $x > 2$\\n3. Irisan: $2 < x < 10$ (Opsi A)."),
    make_q("sma10-b1-20", "Tantangan", "Jumlah semua nilai $x$ yang memenuhi persamaan logaritma $(^x\\log 2)^2 - 3(^x\\log 2) + 2 = 0$ adalah...", ["2 + \\sqrt{2}", "6", "4", "3"], "A", "Faktorkan persamaan kuadrat terhadap $^x\\log 2$: $(^x\\log 2 - 1)(^x\\log 2 - 2) = 0$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $^x\\log 2 = 1 \\implies x = 2$\\n2. $^x\\log 2 = 2 \\implies x^2 = 2 \\implies x = \\sqrt{2}$\\n3. Jumlah $= 2 + \\sqrt{2}$ (Opsi A).")
]

# =========================================================================
# BAB 2: Barisan & Deret (16 questions)
# =========================================================================
b2_add = [
    make_q("sma10-b2-5", "Dasar", "Suku ke-15 dari barisan aritmetika 3, 7, 11, 15, ... adalah...", ["59", "63", "55", "61"], "A", "Gunakan rumus $U_n = a + (n - 1)b$ dengan $a = 3$ dan $b = 4$.", "**Langkah Penyelesaian Terstruktur:**\\n$$U_{15} = 3 + 14(4) = 3 + 56 = 59$$ (Opsi A)."),
    make_q("sma10-b2-6", "Sedang", "Jumlah 20 suku pertama ($S_{20}$) dari deret aritmetika $4 + 7 + 10 + 13 + \\dots$ adalah...", ["650", "620", "680", "640"], "A", "Gunakan rumus $S_n = \\frac{n}{2}(2a + (n - 1)b)$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S_{20} = 10(2(4) + 19(3)) = 10(8 + 57) = 650$$ (Opsi A)."),
    make_q("sma10-b2-7", "Sedang", "Suku ke-7 dari barisan geometri 2, 6, 18, 54, ... adalah...", ["1.458", "486", "4.374", "729"], "A", "Rumus $U_n = a r^{n-1}$ dengan $a = 2$ dan $r = 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$U_7 = 2 \\times 3^6 = 2 \\times 729 = 1.458$$ (Opsi A)."),
    make_q("sma10-b2-8", "Sedang", "Jumlah deret geometri tak hingga $18 + 6 + 2 + \\frac{2}{3} + \\dots$ adalah...", ["27", "24", "36", "18"], "A", "Rumus $S_\\infty = \\frac{a}{1 - r}$ dengan $a = 18$ dan $r = 1/3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S_\\infty = \\frac{18}{1 - \\frac{1}{3}} = 18 \\times \\frac{3}{2} = 27$$ (Opsi A)."),
    make_q("sma10-b2-9", "Sedang", "Dari suatu barisan aritmetika diketahui $U_3 = 11$ dan $U_8 = 26$. Nilai $a$ dan $b$ berturut-turut adalah...", ["5 dan 3", "3 dan 5", "2 dan 4", "4 dan 3"], "A", "$5b = U_8 - U_3 = 15 \\implies b = 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$a = 11 - 2(3) = 5, \\quad b = 3$$ (Opsi A)."),
    make_q("sma10-b2-10", "Sedang", "Banyaknya suku pada barisan aritmetika 5, 9, 13, 17, ..., 121 adalah...", ["30", "29", "31", "28"], "A", "$5 + (n - 1)4 = 121 \\implies 4(n - 1) = 116$.", "**Langkah Penyelesaian Terstruktur:**\\n$$n - 1 = 29 \\implies n = 30$$ (Opsi A)."),
    make_q("sma10-b2-11", "Sedang", "Sebuah bola dijatuhkan dari ketinggian 12 meter dan memantul dengan rasio $\\frac{2}{3}$. Panjang lintasan seluruh pantulan bola hingga berhenti adalah...", ["60 meter", "48 meter", "72 meter", "36 meter"], "A", "Rumus pantulan bola: $S = h \\times \\frac{b + a}{b - a}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S = 12 \\times \\frac{3 + 2}{3 - 2} = 12 \\times 5 = 60\\text{ meter}$$ (Opsi A)."),
    make_q("sma10-b2-12", "Sedang", "Barisan terdepan gedung pertunjukan memiliki 15 kursi. Setiap baris di belakangnya bertambah 3 kursi. Jika ada 12 baris, total kursi adalah...", ["378 kursi", "360 kursi", "396 kursi", "350 kursi"], "A", "$S_{12} = 6(2(15) + 11(3))$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S_{12} = 6(30 + 33) = 6 \\times 63 = 378\\text{ kursi}$$ (Opsi A)."),
    make_q("sma10-b2-13", "Sedang", "Gaji seorang karyawan bertambah tetap Rp200.000,00 setiap tahunnya dari gaji awal Rp4.000.000,00 per bulan. Total seluruh gaji yang diterima selama 5 tahun bekerja adalah...", ["Rp264.000.000,00", "Rp240.000.000,00", "Rp250.000.000,00", "Rp275.000.000,00"], "A", "Total gaji $= 12 \\times S_5$ (deret aritmetika tahunan).", "**Langkah Penyelesaian Terstruktur:**\\n1. $S_5 = \\frac{5}{2}(8.000.000 + 4(200.000)) = 22.000.000$\\n2. Total $= 12 \\times 22.000.000 = \\text{Rp}264.000.000,00$ (Opsi A)."),
    make_q("sma10-b2-14", "Sedang", "Tiga bilangan membentuk barisan geometri dengan hasil kali 216 dan jumlah 26. Suku kedua (tengah) barisan tersebut adalah...", ["6", "8", "4", "9"], "A", "Hasil kali tiga suku berurutan geometri: $(U_2)^3 = 216$.", "**Langkah Penyelesaian Terstruktur:**\\n$$a^3 = 216 \\implies a = 6$$ (Opsi A)."),
    make_q("sma10-b2-15", "Sedang", "Jumlah $n$ suku pertama deret aritmetika adalah $S_n = 2n^2 + 3n$. Suku ke-8 ($U_8$) deret tersebut adalah...", ["33", "35", "31", "37"], "A", "$U_8 = S_8 - S_7$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S_8 = 2(64) + 24 = 152, \\quad S_7 = 2(49) + 21 = 119 \\implies U_8 = 33$$ (Opsi A)."),
    make_q("sma10-b2-16", "Tantangan", "Antara bilangan 3 dan 48 disisipkan 3 bilangan sehingga membentuk barisan geometri baru. Rasio barisan baru adalah...", ["2", "3", "4", "1,5"], "A", "Rumus rasio sisipan: $r' = \\sqrt[k+1]{\\frac{b}{a}}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$r' = \\sqrt[4]{\\frac{48}{3}} = \\sqrt[4]{16} = 2$$ (Opsi A)."),
    make_q("sma10-b2-17", "Tantangan", "Jumlah suku nomor ganjil deret geometri tak hingga adalah 18, dan jumlah seluruh suku adalah 24. Rasio deret tersebut adalah...", ["\\frac{1}{3}", "\\frac{1}{2}", "\\frac{1}{4}", "\\frac{2}{3}"], "A", "$\\frac{S_{\\text{ganjil}}}{S} = \\frac{1}{1 + r} = \\frac{18}{24} = \\frac{3}{4}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$3(1 + r) = 4 \\implies 3r = 1 \\implies r = \\frac{1}{3}$$ (Opsi A)."),
    make_q("sma10-b2-18", "Tantangan", "Tali dipotong menjadi 6 bagian membentuk barisan geometri. Potongan terpendek 3 cm dan terpanjang 96 cm. Panjang tali mula-mula adalah...", ["189 cm", "192 cm", "186 cm", "195 cm"], "A", "$3 r^5 = 96 \\implies r = 2$. Cari $S_6$.", "**Langkah Penyelesaian Terstruktur:**\\n$$S_6 = \\frac{3(2^6 - 1)}{2 - 1} = 3(63) = 189\\text{ cm}$$ (Opsi A)."),
    make_q("sma10-b2-19", "Tantangan", "Jika $(k - 2), (k + 1), (2k + 2)$ merupakan tiga suku berurutan barisan geometri positif, maka nilai $k$ adalah...", ["5", "4", "3", "6"], "A", "Syarat geometri: $(k + 1)^2 = (k - 2)(2k + 2)$.", "**Langkah Penyelesaian Terstruktur:**\\n$$k^2 + 2k + 1 = 2k^2 - 2k - 4 \\implies k^2 - 4k - 5 = 0 \\implies k = 5$$ (Opsi A)."),
    make_q("sma10-b2-20", "Tantangan", "Jumlah 10 suku pertama deret $1 \\cdot 2 + 2 \\cdot 3 + 3 \\cdot 4 + \\dots + 10 \\cdot 11$ adalah...", ["440", "420", "460", "400"], "A", "$U_n = n^2 + n$. Jumlahkan $\\sum n^2 + \\sum n$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{10 \\times 11 \\times 21}{6} + \\frac{10 \\times 11}{2} = 385 + 55 = 440$$ (Opsi A).")
]

# =========================================================================
# BAB 3: Vektor dan Operasinya (16 questions)
# =========================================================================
b3_add = [
    make_q("sma10-b3-5", "Dasar", "Panjang vektor $\\vec{v} = \\begin{pmatrix} 6 \\\\ -8 \\end{pmatrix}$ adalah...", ["10", "14", "12", "8"], "A", "Rumus $|\\vec{v}| = \\sqrt{x^2 + y^2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$|\\vec{v}| = \\sqrt{6^2 + (-8)^2} = \\sqrt{100} = 10$$ (Opsi A)."),
    make_q("sma10-b3-6", "Sedang", "Diketahui vektor $\\vec{a} = 3\\vec{i} - 2\\vec{j}$ dan $\\vec{b} = -\\vec{i} + 5\\vec{j}$. Hasil dari $2\\vec{a} + 3\\vec{b}$ adalah...", ["3\\vec{i} + 11\\vec{j}", "5\\vec{i} + 11\\vec{j}", "3\\vec{i} + 9\\vec{j}", "4\\vec{i} + 11\\vec{j}"], "A", "Jumlahkan komponen $\\vec{i}$ dan $\\vec{j}$ secara terpisah.", "**Langkah Penyelesaian Terstruktur:**\\n$$2(3\\vec{i} - 2\\vec{j}) + 3(-\\vec{i} + 5\\vec{j}) = 3\\vec{i} + 11\\vec{j}$$ (Opsi A)."),
    make_q("sma10-b3-7", "Sedang", "Jika titik $A(2, -3)$ dan $B(7, 9)$, maka vektor $\\vec{AB}$ adalah...", ["\\begin{pmatrix} 5 \\\\ 12 \\end{pmatrix}", "\\begin{pmatrix} 9 \\\\ 6 \\end{pmatrix}", "\\begin{pmatrix} -5 \\\\ -12 \\end{pmatrix}", "\\begin{pmatrix} 5 \\\\ 6 \\end{pmatrix}"], "A", "$\\vec{AB} = B - A$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{AB} = \\begin{pmatrix} 7 - 2 \\\\ 9 - (-3) \\end{pmatrix} = \\begin{pmatrix} 5 \\\\ 12 \\end{pmatrix}$$ (Opsi A)."),
    make_q("sma10-b3-8", "Sedang", "Hasil perkalian skalar (dot product) $\\vec{u} = \\begin{pmatrix} 4 \\\\ -2 \\\\ 5 \\end{pmatrix}$ dan $\\vec{v} = \\begin{pmatrix} 3 \\\\ 6 \\\\ 1 \\end{pmatrix}$ adalah...", ["5", "9", "7", "3"], "A", "$\\vec{u} \\cdot \\vec{v} = x_1 x_2 + y_1 y_2 + z_1 z_2$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{u} \\cdot \\vec{v} = 12 - 12 + 5 = 5$$ (Opsi A)."),
    make_q("sma10-b3-9", "Sedang", "Vektor satuan yang searah dengan $\\vec{a} = \\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix}$ adalah...", ["\\begin{pmatrix} \\frac{3}{5} \\\\ \\frac{4}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{4}{5} \\\\ \\frac{3}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{3}{7} \\\\ \\frac{4}{7} \\end{pmatrix}", "\\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}"], "A", "Bagi komponen vektor dengan panjangnya ($|\\vec{a}| = 5$).", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{e} = \\frac{1}{5}\\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix} = \\begin{pmatrix} \\frac{3}{5} \\\\ \\frac{4}{5} \\end{pmatrix}$$ (Opsi A)."),
    make_q("sma10-b3-10", "Sedang", "Vektor $\\vec{p} = \\begin{pmatrix} x \\\\ 4 \\end{pmatrix}$ dan $\\vec{q} = \\begin{pmatrix} 6 \\\\ -3 \\end{pmatrix}$ saling tegak lurus. Nilai $x$ adalah...", ["2", "3", "-2", "4"], "A", "Syarat tegak lurus: $\\vec{p} \\cdot \\vec{q} = 0$.", "**Langkah Penyelesaian Terstruktur:**\\n$$6x - 12 = 0 \\implies x = 2$$ (Opsi A)."),
    make_q("sma10-b3-11", "Sedang", "Besar sudut antara dua vektor $\\vec{a} = \\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix}$ dan $\\vec{b} = \\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}$ adalah...", ["45^\\circ", "30^\\circ", "60^\\circ", "90^\\circ"], "A", "$\\cos \\theta = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{a}||\\vec{b}|}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\cos \\theta = \\frac{1}{\\sqrt{1} \\cdot \\sqrt{2}} = \\frac{1}{2}\\sqrt{2} \\implies \\theta = 45^\\circ$$ (Opsi A)."),
    make_q("sma10-b3-12", "Sedang", "Panjang proyeksi skalar ortogonal vektor $\\vec{u} = \\begin{pmatrix} 2 \\\\ 4 \\end{pmatrix}$ pada vektor $\\vec{v} = \\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix}$ adalah...", ["\\frac{22}{5}", "4", "\\frac{24}{5}", "5"], "A", "Rumus $|\\vec{c}| = \\frac{\\vec{u} \\cdot \\vec{v}}{|\\vec{v}|}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{2(3) + 4(4)}{\\sqrt{3^2 + 4^2}} = \\frac{22}{5}$$ (Opsi A)."),
    make_q("sma10-b3-13", "Sedang", "Titik $M$ membagi $AB$ dengan perbandingan $AM : MB = 2 : 1$. Jika $A(1, 4)$ dan $B(7, 10)$, koordinat $M$ adalah...", ["(5, 8)", "(4, 7)", "(5, 7)", "(6, 8)"], "A", "$M = \\frac{2B + A}{3}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$M = \\left(\\frac{14+1}{3}, \\frac{20+4}{3}\\right) = (5, 8)$$ (Opsi A)."),
    make_q("sma10-b3-14", "Sedang", "Perahu bergerak dengan kelajuan 8 m/s tegak lurus arus air berkecepatan 6 m/s. Kecepatan resultan perahu adalah...", ["10 m/s", "14 m/s", "12 m/s", "9 m/s"], "A", "Resultan Pythagoras: $v = \\sqrt{8^2 + 6^2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$v = \\sqrt{64 + 36} = 10\\text{ m/s}$$ (Opsi A)."),
    make_q("sma10-b3-15", "Sedang", "Diketahui $|\\vec{a}| = 4$, $|\\vec{b}| = 6$, dan sudut antara keduanya $60^\\circ$. Nilai $\\vec{a} \\cdot \\vec{b}$ adalah...", ["12", "12\\sqrt{3}", "24", "18"], "A", "$\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}| \\cos 60^\\circ$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{a} \\cdot \\vec{b} = 4 \\times 6 \\times \\frac{1}{2} = 12$$ (Opsi A)."),
    make_q("sma10-b3-16", "Tantangan", "Jika $|\\vec{u}| = 5$, $|\\vec{v}| = 3$, dan $|\\vec{u} - \\vec{v}| = 7$, maka $|\\vec{u} + \\vec{v}|$ adalah...", ["\\sqrt{19}", "5", "4\\sqrt{2}", "\\sqrt{21}"], "A", "Identitas jajar genjang: $|\\vec{u} + \\vec{v}|^2 + |\\vec{u} - \\vec{v}|^2 = 2(|\\vec{u}|^2 + |\\vec{v}|^2)$.", "**Langkah Penyelesaian Terstruktur:**\\n$$|\\vec{u} + \\vec{v}|^2 + 49 = 2(25 + 9) = 68 \\implies |\\vec{u} + \\vec{v}| = \\sqrt{19}$$ (Opsi A)."),
    make_q("sma10-b3-17", "Tantangan", "Vektor proyeksi ortogonal dari $\\vec{a} = \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix}$ pada $\\vec{b} = \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix}$ adalah...", ["\\begin{pmatrix} \\frac{8}{5} \\\\ \\frac{4}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{4}{5} \\\\ \\frac{8}{5} \\end{pmatrix}", "\\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}", "\\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix}"], "A", "$\\vec{p} = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{b}|^2} \\vec{b}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{p} = \\frac{4}{5}\\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix} = \\begin{pmatrix} \\frac{8}{5} \\\\ \\frac{4}{5} \\end{pmatrix}$$ (Opsi A)."),
    make_q("sma10-b3-18", "Tantangan", "Titik $A(1, 2, 3)$, $B(2, 4, 5)$, dan $C(x, 8, y)$ kolinier (segaris). Nilai dari $x + y$ adalah...", ["13", "14", "12", "15"], "A", "Rasio vektor: $\\vec{BC} = 2\\vec{AB}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x - 2 = 2(1) \\implies x = 4; \\quad y - 5 = 2(2) \\implies y = 9 \\implies x + y = 13$$ (Opsi A)."),
    make_q("sma10-b3-19", "Tantangan", "Pada segitiga $ABC$, diketahui $\\vec{AB} = \\vec{u}$ dan $\\vec{AC} = \\vec{v}$. Jika $D$ titik tengah $BC$, vektor $\\vec{AD}$ adalah...", ["\\frac{1}{2}(\\vec{u} + \\vec{v})", "\\frac{1}{2}(\\vec{u} - \\vec{v})", "\\vec{u} + \\frac{1}{2}\\vec{v}", "\\frac{1}{2}\\vec{u} + \\vec{v}"], "A", "Vektor posisi titik tengah $D = \\frac{B + C}{2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\vec{AD} = \\frac{1}{2}(\\vec{u} + \\vec{v})$$ (Opsi A)."),
    make_q("sma10-b3-20", "Tantangan", "Dua gaya $F_1 = 10\\text{ N}$ arah $0^\\circ$ dan $F_2 = 10\\text{ N}$ arah $60^\\circ$ diimbangi oleh gaya $F_3$. Besar gaya $F_3$ adalah...", ["10\\sqrt{3}\\text{ N}", "15\\text{ N}", "20\\text{ N}", "10\\sqrt{2}\\text{ N}"], "A", "Resultan gaya $F_1$ dan $F_2$: $R = \\sqrt{F_1^2 + F_2^2 + 2F_1 F_2 \\cos 60^\\circ}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$R = \\sqrt{100 + 100 + 100} = \\sqrt{300} = 10\\sqrt{3}\\text{ N}$$ (Opsi A).")
]

# =========================================================================
# BAB 4: Trigonometri (16 questions)
# =========================================================================
b4_add = [
    make_q("sma10-b4-5", "Dasar", "Nilai dari $\\cos 60^\\circ + \\sin 30^\\circ$ adalah...", ["1", "\\frac{1}{2}\\sqrt{3}", "\\frac{1}{2}", "\\sqrt{3}"], "A", "$\\cos 60^\\circ = 1/2$ dan $\\sin 30^\\circ = 1/2$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{1}{2} + \\frac{1}{2} = 1$$ (Opsi A)."),
    make_q("sma10-b4-6", "Sedang", "Jika $\\sin A = \\frac{3}{5}$ dengan $A$ lancip, maka nilai $\\tan A$ adalah...", ["\\frac{3}{4}", "\\frac{4}{3}", "\\frac{4}{5}", "\\frac{3}{5}"], "A", "Tripel Pythagoras 3-4-5, sisi samping $= 4$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\tan A = \\frac{\\text{depan}}{\\text{samping}} = \\frac{3}{4}$$ (Opsi A)."),
    make_q("sma10-b4-7", "Sedang", "Nilai dari $\\sin 150^\\circ$ adalah...", ["\\frac{1}{2}", "-\\frac{1}{2}", "\\frac{1}{2}\\sqrt{3}", "-\\frac{1}{2}\\sqrt{3}"], "A", "$\\sin(180^\\circ - 30^\\circ) = \\sin 30^\\circ = \\frac{1}{2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\sin 150^\\circ = \\frac{1}{2}$$ (Opsi A)."),
    make_q("sma10-b4-8", "Sedang", "Nilai dari $\\cos 240^\\circ$ adalah...", ["-\\frac{1}{2}", "\\frac{1}{2}", "-\\frac{1}{2}\\sqrt{3}", "\\frac{1}{2}\\sqrt{3}"], "A", "Kuadran III: $\\cos(180^\\circ + 60^\\circ) = -\\cos 60^\\circ = -\\frac{1}{2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\cos 240^\\circ = -\\frac{1}{2}$$ (Opsi A)."),
    make_q("sma10-b4-9", "Sedang", "Bentuk sederhana dari $(1 - \\sin^2 \\theta)(1 + \\tan^2 \\theta)$ adalah...", ["1", "\\cos^2 \\theta", "\\sin^2 \\theta", "\\tan^2 \\theta"], "A", "$1 - \\sin^2 \\theta = \\cos^2 \\theta$ dan $1 + \\tan^2 \\theta = \\sec^2 \\theta$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\cos^2 \\theta \\times \\frac{1}{\\cos^2 \\theta} = 1$$ (Opsi A)."),
    make_q("sma10-b4-10", "Sedang", "Pengamat melihat puncak menara dengan sudut elevasi $45^\\circ$ dari jarak mendatar 30 meter. Tinggi menara adalah...", ["30 meter", "30\\sqrt{3} meter", "15 meter", "15\\sqrt{2} meter"], "A", "$\\tan 45^\\circ = t / 30 \\implies t = 30$.", "**Langkah Penyelesaian Terstruktur:**\\n$$t = 30 \\times \\tan 45^\\circ = 30\\text{ meter}$$ (Opsi A)."),
    make_q("sma10-b4-11", "Sedang", "Pada segitiga $ABC$, sisi $a = 6\\text{ cm}$, sudut $A = 30^\\circ$, dan sudut $B = 45^\\circ$. Panjang sisi $b$ adalah...", ["6\\sqrt{2}\\text{ cm}", "3\\sqrt{2}\\text{ cm}", "6\\sqrt{3}\\text{ cm}", "4\\sqrt{2}\\text{ cm}"], "A", "Aturan sinus: $\\frac{a}{\\sin A} = \\frac{b}{\\sin B}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$b = \\frac{6 \\times \\sin 45^\\circ}{\\sin 30^\\circ} = \\frac{6 \\times \\frac{1}{2}\\sqrt{2}}{\\frac{1}{2}} = 6\\sqrt{2}\\text{ cm}$$ (Opsi A)."),
    make_q("sma10-b4-12", "Sedang", "Pada segitiga $ABC$, diketahui $b = 5\\text{ cm}$, $c = 8\\text{ cm}$, dan sudut $A = 60^\\circ$. Panjang sisi $a$ adalah...", ["7 cm", "8 cm", "6 cm", "\\sqrt{53} cm"], "A", "Aturan cosinus: $a^2 = b^2 + c^2 - 2bc\\cos 60^\\circ$.", "**Langkah Penyelesaian Terstruktur:**\\n$$a^2 = 25 + 64 - 80(1/2) = 49 \\implies a = 7\\text{ cm}$$ (Opsi A)."),
    make_q("sma10-b4-13", "Sedang", "Luas segitiga dengan dua sisi 10 cm dan 12 cm serta sudut apit $30^\\circ$ adalah...", ["30 cm^2", "60 cm^2", "30\\sqrt{3} cm^2", "45 cm^2"], "A", "Luas $= \\frac{1}{2} a b \\sin C$.", "**Langkah Penyelesaian Terstruktur:**\\n$$L = \\frac{1}{2} \\times 10 \\times 12 \\times \\sin 30^\\circ = 60 \\times \\frac{1}{2} = 30\\text{ cm}^2$$ (Opsi A)."),
    make_q("sma10-b4-14", "Sedang", "Jika $\\tan \\alpha = -\\frac{4}{3}$ di Kuadran II, maka nilai $\\cos \\alpha$ adalah...", ["-\\frac{3}{5}", "\\frac{3}{5}", "-\\frac{4}{5}", "\\frac{4}{5}"], "A", "Di Kuadran II, cosinus bernilai negatif: $-3/5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\cos \\alpha = -\\frac{3}{5}$$ (Opsi A)."),
    make_q("sma10-b4-15", "Sedang", "Nilai dari $\\frac{\\sin 120^\\circ \\cdot \\cos 300^\\circ}{\\tan 225^\\circ}$ adalah...", ["\\frac{1}{4}\\sqrt{3}", "\\frac{1}{2}\\sqrt{3}", "\\frac{1}{4}", "\\frac{1}{2}"], "A", "$\\sin 120^\\circ = \\frac{1}{2}\\sqrt{3}, \\cos 300^\\circ = \\frac{1}{2}, \\tan 225^\\circ = 1$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{\\frac{1}{2}\\sqrt{3} \\times \\frac{1}{2}}{1} = \\frac{1}{4}\\sqrt{3}$$ (Opsi A)."),
    make_q("sma10-b4-16", "Tantangan", "Kapal berlayar dari $A$ arah $060^\\circ$ sejauh 20 mil ke $B$, lalu arah $120^\\circ$ sejauh 20 mil ke $C$. Jarak $A$ ke $C$ adalah...", ["20\\sqrt{3} mil", "20 mil", "40 mil", "30 mil"], "A", "Sudut apit $B$ adalah $120^\\circ$. Gunakan aturan cosinus.", "**Langkah Penyelesaian Terstruktur:**\\n$$AC = \\sqrt{400 + 400 - 800(-1/2)} = \\sqrt{1.200} = 20\\sqrt{3}\\text{ mil}$$ (Opsi A)."),
    make_q("sma10-b4-17", "Tantangan", "Bentuk sederhana dari $\\frac{\\sin x}{1 + \\cos x} + \\frac{1 + \\cos x}{\\sin x}$ adalah...", ["2\\csc x", "2\\sec x", "2\\tan x", "\\csc x"], "A", "Samakan penyebut: $\\frac{\\sin^2 x + (1 + \\cos x)^2}{(1 + \\cos x)\\sin x}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{2 + 2\\cos x}{(1 + \\cos x)\\sin x} = \\frac{2}{\\sin x} = 2\\csc x$$ (Opsi A)."),
    make_q("sma10-b4-18", "Tantangan", "Himpunan penyelesaian $2\\sin x - \\sqrt{3} = 0$ untuk $0^\\circ \\le x \\le 360^\\circ$ adalah...", ["{60^\\circ, 120^\\circ}", "{30^\\circ, 150^\\circ}", "{60^\\circ, 240^\\circ}", "{60^\\circ, 300^\\circ}"], "A", "$\\sin x = \\frac{1}{2}\\sqrt{3}$ di Kuadran I dan II.", "**Langkah Penyelesaian Terstruktur:**\\n$$x = 60^\\circ \\text{ dan } x = 180^\\circ - 60^\\circ = 120^\\circ$$ (Opsi A)."),
    make_q("sma10-b4-19", "Tantangan", "Segitiga dengan sisi 5 cm, 6 cm, dan 7 cm memiliki kosinus sudut terbesar sama dengan...", ["\\frac{1}{5}", "\\frac{2}{5}", "\\frac{1}{7}", "\\frac{1}{6}"], "A", "Sudut terbesar di depan sisi 7. Aturan cosinus: $\\cos C = \\frac{25 + 36 - 49}{60}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\cos C = \\frac{12}{60} = \\frac{1}{5}$$ (Opsi A)."),
    make_q("sma10-b4-20", "Tantangan", "Nilai dari $\\sin^2 15^\\circ + \\sin^2 75^\\circ$ adalah...", ["1", "\\frac{1}{2}", "\\frac{1}{2}\\sqrt{3}", "2"], "A", "$\\sin 75^\\circ = \\cos 15^\\circ$. Gunakan $\\sin^2 \\theta + \\cos^2 \\theta = 1$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\sin^2 15^\\circ + \\cos^2 15^\\circ = 1$$ (Opsi A).")
]

# =========================================================================
# BAB 5: SPLTV & SPtLDV (16 questions)
# =========================================================================
b5_add = [
    make_q("sma10-b5-5", "Dasar", "Titik berikut yang berada di dalam daerah penyelesaian $2x + 3y \\le 12$ adalah...", ["(1, 2)", "(4, 3)", "(5, 2)", "(3, 4)"], "A", "Uji titik $(1, 2)$: $2(1) + 3(2) = 8 \\le 12$ (benar).", "**Langkah Penyelesaian Terstruktur:**\\n$$2(1) + 3(2) = 8 \\le 12$$ (Opsi A)."),
    make_q("sma10-b5-6", "Sedang", "Diketahui SPLTV $\\begin{cases} x + y + z = 6 \\\\ x + 2y + z = 8 \\\\ 2x - y + z = 3 \\end{cases}$. Nilai $x$ adalah...", ["1", "2", "3", "4"], "A", "Kurangkan pers 2 dengan pers 1: $y = 2$. Lalu selesaikan untuk $x$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $y = 2 \\implies x + z = 4$\\n2. $2x - 2 + z = 3 \\implies 2x + z = 5$\\n3. $x = 5 - 4 = 1$ (Opsi A)."),
    make_q("sma10-b5-7", "Sedang", "Harga 2 kg mangga, 1 kg apel, dan 3 kg jeruk Rp87.000,00. Persamaan linear yang sesuai adalah...", ["2x + y + 3z = 87.000", "x + 2y + 3z = 87.000", "3x + y + 2z = 87.000", "2x + 3y + z = 87.000"], "A", "Kalikan kuantitas masing-masing buah dengan variabel harga.", "**Langkah Penyelesaian Terstruktur:**\\n$$2x + y + 3z = 87.000$$ (Opsi A)."),
    make_q("sma10-b5-8", "Sedang", "Daerah himpunan penyelesaian sistem $x + y \\ge 4, 2x + y \\le 6, x \\ge 0, y \\ge 0$ terletak pada...", ["Kuadran I", "Kuadran II", "Kuadran III", "Kuadran IV"], "A", "Syarat $x \\ge 0$ dan $y \\ge 0$ membatasi daerah hanya di Kuadran I.", "**Langkah Penyelesaian Terstruktur:**\\nDaerah berada di **Kuadran I** (Opsi A)."),
    make_q("sma10-b5-9", "Sedang", "Nilai maksimum dari $f(x, y) = 3x + 4y$ pada titik-titik pojok $(0, 0), (4, 0), (2, 3), (0, 4)$ adalah...", ["18", "16", "12", "20"], "A", "Uji $f(2, 3) = 3(2) + 4(3) = 18$.", "**Langkah Penyelesaian Terstruktur:**\\n$$f(2, 3) = 6 + 12 = 18$$ (Opsi A)."),
    make_q("sma10-b5-10", "Sedang", "Titik potong garis pembatas $3x - 2y = 6$ dengan sumbu koordinat adalah...", ["(2, 0) dan (0, -3)", "(3, 0) dan (0, -2)", "(-2, 0) dan (0, 3)", "(0, 2) dan (-3, 0)"], "A", "Masukkan $y=0 \\implies x=2$ dan $x=0 \\implies y=-3$.", "**Langkah Penyelesaian Terstruktur:**\\nTitik potongnya adalah **(2, 0) dan (0, -3)** (Opsi A)."),
    make_q("sma10-b5-11", "Sedang", "Total umur Ali, Budi, dan Cici adalah 45 tahun. Budi 2 tahun lebih muda dari Ali, Cici 5 tahun lebih muda dari Budi. Umur Ali adalah...", ["18 tahun", "16 tahun", "15 tahun", "20 tahun"], "A", "$A + (A - 2) + (A - 7) = 45 \\implies 3A = 54$.", "**Langkah Penyelesaian Terstruktur:**\\n$$A = 18\\text{ tahun}$$ (Opsi A)."),
    make_q("sma10-b5-12", "Sedang", "Pedagang buah memiliki gerobak muatan maksimal 100 kg dan modal Rp1.200.000,00. Harga beli apel Rp15.000/kg dan jeruk Rp10.000/kg. Model pertidaksamaan yang tepat adalah...", ["x + y \\le 100, \\quad 3x + 2y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\ge 100, \\quad 3x + 2y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\le 100, \\quad 2x + 3y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\le 120, \\quad 3x + 2y \\le 100, \\quad x \\ge 0, y \\ge 0"], "A", "Kapasitas: $x + y \\le 100$. Modal: $15.000x + 10.000y \\le 1.200.000$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x + y \\le 100, \\quad 3x + 2y \\le 240, \\quad x \\ge 0, y \\ge 0$$ (Opsi A)."),
    make_q("sma10-b5-13", "Sedang", "Jika $(x, y, z)$ memenuhi sistem $\\begin{cases} x + y = 5 \\\\ y + z = 7 \\\\ x + z = 6 \\end{cases}$, nilai $x + y + z$ adalah...", ["9", "10", "8", "12"], "A", "Jumlahkan ketiga persamaan: $2(x + y + z) = 18$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x + y + z = 9$$ (Opsi A)."),
    make_q("sma10-b5-14", "Sedang", "Tempat parkir seluas $360\\text{ m}^2$ memuat sedan ($6\\text{ m}^2$) dan bus ($24\\text{ m}^2$). Maksimal 30 kendaraan. Sistem pertidaksamaannya adalah...", ["x + y \\le 30, \\quad x + 4y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\le 30, \\quad 4x + y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\ge 30, \\quad x + 4y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\le 30, \\quad 6x + 24y \\ge 360, \\quad x \\ge 0, y \\ge 0"], "A", "$6x + 24y \\le 360 \\implies x + 4y \\le 60$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x + y \\le 30, \\quad x + 4y \\le 60, \\quad x \\ge 0, y \\ge 0$$ (Opsi A)."),
    make_q("sma10-b5-15", "Sedang", "Nilai minimum fungsi objektif $Z = 5x + 2y$ pada daerah $x + 2y \\ge 8, x \\ge 0, y \\ge 0$ adalah...", ["8", "10", "12", "16"], "A", "Uji titik pojok $(8, 0)$ dan $(0, 4)$. $Z(0, 4) = 8$.", "**Langkah Penyelesaian Terstruktur:**\\n$$Z_{\\min} = 5(0) + 2(4) = 8$$ (Opsi A)."),
    make_q("sma10-b5-16", "Tantangan", "Diketahui sistem $\\frac{1}{x} + \\frac{1}{y} = 5$, $\\frac{1}{y} + \\frac{1}{z} = 7$, $\\frac{1}{x} + \\frac{1}{z} = 6$. Nilai $x + y + z$ adalah...", ["\\frac{13}{12}", "\\frac{11}{12}", "1", "\\frac{7}{6}"], "A", "Misalkan $a, b, c$. Jumlahkan: $a + b + c = 9 \\implies x = 1/2, y = 1/3, z = 1/4$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x + y + z = \\frac{1}{2} + \\frac{1}{3} + \\frac{1}{4} = \\frac{13}{12}$$ (Opsi A)."),
    make_q("sma10-b5-17", "Tantangan", "Pabrik memproduksi barang A (untung 40.000) dan B (untung 30.000). Titik ekstrim daerah layak adalah $(0, 0), (50, 0), (40, 20), (20, 50), (0, 60)$. Untung maksimum adalah...", ["Rp2.300.000,00", "Rp2.200.000,00", "Rp2.000.000,00", "Rp2.400.000,00"], "A", "Uji $(20, 50)$: $40.000(20) + 30.000(50) = 800.000 + 1.500.000 = 2.300.000$.", "**Langkah Penyelesaian Terstruktur:**\\nKeuntungan maksimum adalah **Rp2.300.000,00** (Opsi A)."),
    make_q("sma10-b5-18", "Tantangan", "Agar SPLTV $\\begin{cases} x + 2y - z = 4 \\\\ 2x - y + z = 3 \\\\ 3x + y + az = 7 \\end{cases}$ memiliki tak hingga banyak penyelesaian, nilai $a$ adalah...", ["0", "1", "-1", "2"], "A", "Jumlahkan pers 1 dan 2: $3x + y + 0z = 7$.", "**Langkah Penyelesaian Terstruktur:**\\nKoefisien $z$ harus cocok: $a = 0$ (Opsi A)."),
    make_q("sma10-b5-19", "Tantangan", "Titik potong kurva $y = x^2 - 4$ dan garis $y = 2x - 1$ adalah...", ["(-1, -3) dan (3, 5)", "(-2, 0) dan (2, 0)", "(1, 1) dan (3, 5)", "(0, -4) dan (2, 3)"], "A", "$x^2 - 2x - 3 = 0 \\implies x = 3$ atau $x = -1$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x = 3 \\implies y = 5; \\quad x = -1 \\implies y = -3$$ (Opsi A)."),
    make_q("sma10-b5-20", "Tantangan", "Peserta menjawab 13 soal (A, B, C) dengan skor 62. Bobot: A=2, B=4, C=6. Banyak soal B adalah dua kali soal A. Banyak soal C adalah...", ["7", "6", "8", "5"], "A", "Susun sistem: $3A + C = 13$ dan $10A + 6C = 62$.", "**Langkah Penyelesaian Terstruktur:**\\n$$10A + 6(13 - 3A) = 62 \\implies 8A = 16 \\implies A = 2 \\implies C = 7$$ (Opsi A).")
]

# =========================================================================
# BAB 6: Fungsi Kuadrat (16 questions)
# =========================================================================
b6_add = [
    make_q("sma10-b6-5", "Dasar", "Sumbu simetri dari fungsi $f(x) = x^2 - 6x + 8$ adalah garis...", ["x = 3", "x = -3", "x = 6", "x = 4"], "A", "$x_p = -b / (2a) = 6 / 2 = 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x = -\\frac{-6}{2} = 3$$ (Opsi A)."),
    make_q("sma10-b6-6", "Sedang", "Titik puncak dari fungsi kuadrat $f(x) = x^2 - 4x - 5$ adalah...", ["(2, -9)", "(2, -5)", "(-2, 7)", "(4, -5)"], "A", "$x_p = 2$, lalu $f(2) = 4 - 8 - 5 = -9$.", "**Langkah Penyelesaian Terstruktur:**\\nPuncak berada di **(2, -9)** (Opsi A)."),
    make_q("sma10-b6-7", "Sedang", "Titik potong grafik $f(x) = x^2 - 5x + 6$ dengan sumbu-X adalah...", ["(2, 0) dan (3, 0)", "(-2, 0) dan (-3, 0)", "(1, 0) dan (6, 0)", "(-1, 0) dan (-6, 0)"], "A", "$(x - 2)(x - 3) = 0 \\implies x = 2$ atau $x = 3$.", "**Langkah Penyelesaian Terstruktur:**\\n**(2, 0) dan (3, 0)** (Opsi A)."),
    make_q("sma10-b6-8", "Sedang", "Nilai diskriminan ($D$) dari $f(x) = 2x^2 - 4x + 3$ adalah...", ["-8", "8", "-16", "16"], "A", "$D = b^2 - 4ac = 16 - 24 = -8$.", "**Langkah Penyelesaian Terstruktur:**\\n$$D = (-4)^2 - 4(2)(3) = -8$$ (Opsi A)."),
    make_q("sma10-b6-9", "Sedang", "Jika fungsi kuadrat memiliki $a > 0$ dan $D < 0$, maka grafiknya bersifat...", ["Definit positif (selalu di atas sumbu-X)", "Definit negatif (selalu di bawah sumbu-X)", "Menyinggung sumbu-X", "Memotong sumbu-X di dua titik"], "A", "Kurva selalu bernilai positif untuk setiap $x$.", "**Langkah Penyelesaian Terstruktur:**\\nSifat ini dinamakan **definit positif** (Opsi A)."),
    make_q("sma10-b6-10", "Sedang", "Persamaan fungsi kuadrat yang berpuncak di $(1, -4)$ dan melalui $(0, -3)$ adalah...", ["f(x) = x^2 - 2x - 3", "f(x) = x^2 + 2x - 3", "f(x) = 2x^2 - 4x - 3", "f(x) = x^2 - 2x - 4"], "A", "$f(x) = a(x - 1)^2 - 4$. Melalui $(0, -3) \\implies a = 1$.", "**Langkah Penyelesaian Terstruktur:**\\n$$f(x) = (x - 1)^2 - 4 = x^2 - 2x - 3$$ (Opsi A)."),
    make_q("sma10-b6-11", "Sedang", "Tinggi peluru dinyatakan dengan $h(t) = 40t - 5t^2$ meter. Tinggi maksimum peluru adalah...", ["80 meter", "75 meter", "85 meter", "100 meter"], "A", "$t_{\\max} = -40 / (2 \\times -5) = 4$ detik. $h(4) = 160 - 80 = 80$.", "**Langkah Penyelesaian Terstruktur:**\\n$$h(4) = 40(4) - 5(16) = 80\\text{ meter}$$ (Opsi A)."),
    make_q("sma10-b6-12", "Sedang", "Kawat 80 meter memagari 3 sisi kebun persegi panjang (satu sisi tembok). Luas maksimum kebun adalah...", ["800 m^2", "600 m^2", "400 m^2", "1.000 m^2"], "A", "$p + 2l = 80 \\implies L(l) = l(80 - 2l)$. Puncak di $l = 20, p = 40$.", "**Langkah Penyelesaian Terstruktur:**\\n$$L_{\\max} = 40 \\times 20 = 800\\text{ m}^2$$ (Opsi A)."),
    make_q("sma10-b6-13", "Sedang", "Dua bilangan memiliki selisih 10. Hasil kali minimum kedua bilangan tersebut adalah...", ["-25", "-20", "-16", "-30"], "A", "$P(x) = x(x - 10) = x^2 - 10x$. Minimum di $x = 5 \\implies P(5) = -25$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P_{\\min} = 5(5 - 10) = -25$$ (Opsi A)."),
    make_q("sma10-b6-14", "Sedang", "Roket mencapai $h = 0$ saat $t = 0$ dan $t = 6$, serta mencapai $h = 45$ saat $t = 3$. Persamaan lintasannya adalah...", ["h(t) = -5t^2 + 30t", "h(t) = -5t^2 + 15t", "h(t) = -3t^2 + 18t", "h(t) = -4t^2 + 24t"], "A", "$h(t) = a t(t - 6)$. $45 = a(3)(-3) \\implies a = -5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$h(t) = -5t(t - 6) = -5t^2 + 30t$$ (Opsi A)."),
    make_q("sma10-b6-15", "Sedang", "Grafik fungsi kuadrat $f(x) = ax^2 + bx + c$ memotong sumbu-Y di titik...", ["(0, c)", "(c, 0)", "(0, -c)", "(-c, 0)"], "A", "Masukkan nilai $x = 0 \\implies f(0) = c$.", "**Langkah Penyelesaian Terstruktur:**\\nTitik potong sumbu-Y adalah **(0, c)** (Opsi A)."),
    make_q("sma10-b6-16", "Tantangan", "Garis $y = 2x + k$ menyinggung parabola $y = x^2 - 4x + 10$. Nilai $k$ adalah...", ["1", "2", "-1", "0"], "A", "$x^2 - 6x + (10 - k) = 0$. Syarat menyinggung $D = 0 \\implies 36 - 4(10 - k) = 0$.", "**Langkah Penyelesaian Terstruktur:**\\n$$36 - 40 + 4k = 0 \\implies 4k = 4 \\implies k = 1$$ (Opsi A)."),
    make_q("sma10-b6-17", "Tantangan", "Agar $f(x) = (m - 1)x^2 + 4x + (m - 1)$ selalu bernilai negatif untuk setiap $x \\in \\mathbb{R}$, batas $m$ adalah...", ["m < -1", "m > 3", "-1 < m < 3", "m < 1"], "A", "Syarat definit negatif: $a < 0$ dan $D < 0$.", "**Langkah Penyelesaian Terstruktur:**\\n1. $m < 1$\\n2. $16 - 4(m - 1)^2 < 0 \\implies (m - 1)^2 > 4 \\implies m > 3$ atau $m < -1$\\n3. Irisan: $m < -1$ (Opsi A)."),
    make_q("sma10-b6-18", "Tantangan", "Persamaan kuadrat yang akar-akarnya adalah absis potong $y = 2x^2 - 3x + 1$ dan $y = x^2 + 2x - 5$ adalah...", ["x^2 - 5x + 6 = 0", "x^2 + 5x + 6 = 0", "x^2 - x - 4 = 0", "x^2 + x - 6 = 0"], "A", "Samakan kedua fungsi kuadrat: $2x^2 - 3x + 1 = x^2 + 2x - 5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x^2 - 5x + 6 = 0$$ (Opsi A)."),
    make_q("sma10-b6-19", "Tantangan", "Grafik $f(x) = x^2 + bx + c$ digeser 2 satuan ke kanan dan 3 ke atas menjadi $g(x) = x^2 - 2x + 6$. Nilai $b + c$ adalah...", ["5", "6", "7", "4"], "A", "$g(x) = f(x - 2) + 3$. Samakan koefisien.", "**Langkah Penyelesaian Terstruktur:**\\n$$b - 4 = -2 \\implies b = 2; \\quad 7 - 4 + c = 6 \\implies c = 3 \\implies b + c = 5$$ (Opsi A)."),
    make_q("sma10-b6-20", "Tantangan", "Nilai minimum $f(x) = 2x^2 - 8x + k$ pada interval $[0, 5]$ adalah 3. Nilai $k$ adalah...", ["11", "9", "8", "13"], "A", "Puncak di $x = 2 \\in [0, 5]$. $f(2) = 8 - 16 + k = 3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$k - 8 = 3 \\implies k = 11$$ (Opsi A).")
]

# =========================================================================
# BAB 7: Statistika (16 questions)
# =========================================================================
b7_add = [
    make_q("sma10-b7-5", "Dasar", "Simpangan rata-rata dari data: 4, 6, 8, 10, 12 adalah...", ["2,4", "2,0", "2,8", "3,0"], "A", "Rata-rata $= 8$. $SR = \\frac{4 + 2 + 0 + 2 + 4}{5}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$SR = \\frac{12}{5} = 2{,}4$$ (Opsi A)."),
    make_q("sma10-b7-6", "Sedang", "Varians (ragam) dari data: 2, 4, 6, 8, 10 adalah...", ["8", "6", "10", "\\sqrt{8}"], "A", "Rata-rata $= 6$. Kuadrat selisih $= 16 + 4 + 0 + 4 + 16 = 40$.", "**Langkah Penyelesaian Terstruktur:**\\n$$s^2 = \\frac{40}{5} = 8$$ (Opsi A)."),
    make_q("sma10-b7-7", "Sedang", "Simpangan baku dari data: 3, 5, 7, 9, 11 adalah...", ["2\\sqrt{2}", "8", "\\sqrt{6}", "2\\sqrt{3}"], "A", "Simpangan baku $s = \\sqrt{s^2} = \\sqrt{8} = 2\\sqrt{2}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$s = \\sqrt{8} = 2\\sqrt{2}$$ (Opsi A)."),
    make_q("sma10-b7-8", "Sedang", "Tepi bawah ($L$) dan panjang kelas ($c$) dari interval $41 - 50$ berturut-turut adalah...", ["40,5 dan 10", "41 dan 9", "40,5 dan 9", "41,5 dan 10"], "A", "Tepi bawah $= 41 - 0{,}5 = 40{,}5$. Panjang kelas $= 10$.", "**Langkah Penyelesaian Terstruktur:**\\n$$L = 40{,}5, \\quad c = 10$$ (Opsi A)."),
    make_q("sma10-b7-9", "Sedang", "Titik tengah ($x_i$) dari kelas interval $60 - 64$ adalah...", ["62", "61,5", "62,5", "63"], "A", "Titik tengah $= \\frac{60 + 64}{2} = 62$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x_i = \\frac{60 + 64}{2} = 62$$ (Opsi A)."),
    make_q("sma10-b7-10", "Sedang", "Desil ke-3 ($D_3$) dari 20 data terurut berada pada data ke...", ["6,3", "6", "7", "5,5"], "A", "Letak $D_3 = \\frac{3(20 + 1)}{10} = 6{,}3$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\text{Letak } D_3 = 6{,}3$$ (Opsi A)."),
    make_q("sma10-b7-11", "Sedang", "Kelas modus $51 - 60$, frekuensi 14, frekuensi sebelum 10, sesudah 8, panjang 10. Nilai modusnya adalah...", ["54,5", "55,0", "53,5", "56,0"], "A", "$d_1 = 4, d_2 = 6$. $Mo = 50{,}5 + \\frac{4}{10} \\times 10 = 54{,}5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$Mo = 50{,}5 + 4 = 54{,}5$$ (Opsi A)."),
    make_q("sma10-b7-12", "Sedang", "Median data kelompok ($N = 40$) di kelas $61 - 70$ (frekuensi 10, $f_k$ sebelum 15). Nilai mediannya adalah...", ["65,5", "66,0", "64,5", "65,0"], "A", "$Me = 60{,}5 + \\left(\\frac{20 - 15}{10}\\right)10 = 65{,}5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$Me = 60{,}5 + 5 = 65{,}5$$ (Opsi A)."),
    make_q("sma10-b7-13", "Sedang", "Rata-rata sementara $\\bar{x}_s = 65$, $\\sum f_i d_i = 120$, $\\sum f_i = 40$. Rata-rata sebenarnya adalah...", ["68", "67", "66", "69"], "A", "$\\bar{x} = 65 + \\frac{120}{40} = 68$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\bar{x} = 65 + 3 = 68$$ (Opsi A)."),
    make_q("sma10-b7-14", "Sedang", "Jika data memiliki simpangan baku 4 dan setiap data dikalikan 3 lalu ditambah 5, simpangan baku yang baru adalah...", ["12", "17", "9", "7"], "A", "Penambahan konstanta tidak mengubah $s$. Perkalian mengalikan $s$: $3 \\times 4 = 12$.", "**Langkah Penyelesaian Terstruktur:**\\n$$s_{\\text{baru}} = 3 \\times 4 = 12$$ (Opsi A)."),
    make_q("sma10-b7-15", "Sedang", "Grafik frekuensi kumulatif 'kurang dari' dinamakan...", ["Ogive positif", "Ogive negatif", "Poligon frekuensi", "Histogram"], "A", "Kurva frekuensi kumulatif kurang dari selalu meningkat.", "**Langkah Penyelesaian Terstruktur:**\\nKurva tersebut adalah **Ogive positif** (Opsi A)."),
    make_q("sma10-b7-16", "Tantangan", "Sepuluh data terurut memiliki jangkauan 8. Jika data terbesar 15, maka data terkecil adalah...", ["7", "6", "8", "5"], "A", "$x_{\\min} = 15 - 8 = 7$.", "**Langkah Penyelesaian Terstruktur:**\\n$$x_{\\min} = 7$$ (Opsi A)."),
    make_q("sma10-b7-17", "Tantangan", "Kuartil atas ($Q_3$) data kelompok ($N = 80$) di kelas $71 - 80$ ($L = 70{,}5, f = 20, f_k = 50, c = 10$) bernilai...", ["75,5", "74,5", "76,0", "75,0"], "A", "Letak $Q_3 = 60$. $Q_3 = 70{,}5 + \\frac{60 - 50}{20} \\times 10 = 75{,}5$.", "**Langkah Penyelesaian Terstruktur:**\\n$$Q_3 = 70{,}5 + 5 = 75{,}5$$ (Opsi A)."),
    make_q("sma10-b7-18", "Tantangan", "Rata-rata ujian 70 dengan simpangan baku 8. Jika siswa mendapat nilai 86, skor baku ($z$-score) siswa tersebut adalah...", ["2,0", "1,5", "2,5", "1,75"], "A", "$z = \\frac{86 - 70}{8} = 2{,}0$.", "**Langkah Penyelesaian Terstruktur:**\\n$$z = \\frac{16}{8} = 2{,}0$$ (Opsi A)."),
    make_q("sma10-b7-19", "Tantangan", "Nilai koefisien variasi $KV = 5\\%$ dan simpangan baku $3{,}5$. Rata-rata kelas tersebut adalah...", ["70", "75", "65", "80"], "A", "$\\bar{x} = \\frac{3{,}5}{0{,}05} = 70$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\bar{x} = 70$$ (Opsi A)."),
    make_q("sma10-b7-20", "Tantangan", "Lima bilangan bulat positif terurut memiliki modus tunggal 4, median 6, rata-rata 7. Nilai maksimum datum terbesar adalah...", ["14", "15", "13", "16"], "A", "Data: $4, 4, 6, d, e$. Jumlah $= 35 \\implies d + e = 21$. Agar $e$ maksimal, $d = 7$.", "**Langkah Penyelesaian Terstruktur:**\\n$$e = 21 - 7 = 14$$ (Opsi A).")
]

# =========================================================================
# BAB 8: Peluang (16 questions)
# =========================================================================
b8_add = [
    make_q("sma10-b8-5", "Dasar", "Banyak cara menyusun 3 huruf berbeda dari 7 huruf unik adalah...", ["210", "120", "35", "42"], "A", "Permutasi $P(7, 3) = 7 \\times 6 \\times 5 = 210$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P(7, 3) = 210$$ (Opsi A)."),
    make_q("sma10-b8-6", "Sedang", "Nilai kombinasi $C(8, 3)$ adalah...", ["56", "336", "28", "70"], "A", "$C(8, 3) = \\frac{8 \\times 7 \\times 6}{6} = 56$.", "**Langkah Penyelesaian Terstruktur:**\\n$$C(8, 3) = 56$$ (Opsi A)."),
    make_q("sma10-b8-7", "Sedang", "Dua dadu dilempar bersamaan. Peluang muncul jumlah mata dadu sama dengan 7 adalah...", ["\\frac{1}{6}", "\\frac{5}{36}", "\\frac{7}{36}", "\\frac{1}{12}"], "A", "Ada 6 pasangan berjumlah 7: $6 / 36 = 1/6$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{6}{36} = \\frac{1}{6}$$ (Opsi A)."),
    make_q("sma10-b8-8", "Sedang", "Dari 52 kartu bridge, peluang terambil kartu As atau kartu merah adalah...", ["\\frac{7}{13}", "\\frac{1}{2}", "\\frac{15}{26}", "\\frac{6}{13}"], "A", "$P(A \\cup B) = \\frac{4 + 26 - 2}{52} = \\frac{28}{52} = \\frac{7}{13}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{28}{52} = \\frac{7}{13}$$ (Opsi A)."),
    make_q("sma10-b8-9", "Sedang", "Kantong berisi 5 bola merah dan 3 bola biru. Diambil 2 bola sekaligus. Peluang keduanya merah adalah...", ["\\frac{5}{14}", "\\frac{10}{28}", "\\frac{15}{28}", "\\frac{3}{14}"], "A", "$P = \\frac{C(5, 2)}{C(8, 2)} = \\frac{10}{28} = \\frac{5}{14}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{10}{28} = \\frac{5}{14}$$ (Opsi A)."),
    make_q("sma10-b8-10", "Sedang", "Koin dilempar undi 120 kali. Frekuensi harapan muncul sisi gambar adalah...", ["60 kali", "40 kali", "80 kali", "50 kali"], "A", "$F_h = 120 \\times \\frac{1}{2} = 60$.", "**Langkah Penyelesaian Terstruktur:**\\n$$F_h = 60\\text{ kali}$$ (Opsi A)."),
    make_q("sma10-b8-11", "Sedang", "Dari 10 calon pengurus akan dipilih Ketua, Sekretaris, Bendahara. Banyak susunan yang terbentuk adalah...", ["720", "120", "360", "240"], "A", "Permutasi posisi: $P(10, 3) = 10 \\times 9 \\times 8 = 720$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P(10, 3) = 720$$ (Opsi A)."),
    make_q("sma10-b8-12", "Sedang", "Dalam pertemuan 8 orang, setiap orang saling berjabat tangan satu kali. Total jabat tangan adalah...", ["28", "56", "24", "32"], "A", "Kombinasi $C(8, 2) = \\frac{8 \\times 7}{2} = 28$.", "**Langkah Penyelesaian Terstruktur:**\\n$$C(8, 2) = 28$$ (Opsi A)."),
    make_q("sma10-b8-13", "Sedang", "Peluang lulus matematika 0,85 dan fisika 0,70 (saling bebas). Peluang lulus matematika tapi tidak lulus fisika adalah...", ["0,255", "0,150", "0,595", "0,300"], "A", "$P = 0{,}85 \\times (1 - 0{,}70) = 0{,}255$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = 0{,}85 \\times 0{,}30 = 0{,}255$$ (Opsi A)."),
    make_q("sma10-b8-14", "Sedang", "Kotak berisi 4 bola merah dan 6 bola putih. Diambil 2 bola berturut-turut tanpa pengembalian. Peluang merah lalu putih adalah...", ["\\frac{4}{15}", "\\frac{6}{25}", "\\frac{1}{3}", "\\frac{2}{9}"], "A", "$P = \\frac{4}{10} \\times \\frac{6}{9} = \\frac{4}{15}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{4}{15}$$ (Opsi A)."),
    make_q("sma10-b8-15", "Sedang", "Banyak bilangan ganjil 3 angka berbeda dari angka 1, 2, 3, 4, 5, 6 adalah...", ["60", "72", "48", "90"], "A", "Satuan (1, 3, 5) ada 3 cara. Ratusan 5 cara, puluhan 4 cara: $3 \\times 5 \\times 4 = 60$.", "**Langkah Penyelesaian Terstruktur:**\\n$$3 \\times 5 \\times 4 = 60$$ (Opsi A)."),
    make_q("sma10-b8-16", "Tantangan", "Tujuh orang duduk melingkar di mana 2 orang tertentu harus selalu berdampingan. Banyak susunan posisi duduk adalah...", ["240", "120", "720", "144"], "A", "Siklis 6 unsur: $(6 - 1)! \\times 2! = 120 \\times 2 = 240$.", "**Langkah Penyelesaian Terstruktur:**\\n$$5! \\times 2 = 240$$ (Opsi A)."),
    make_q("sma10-b8-17", "Tantangan", "Banyak kata yang dapat disusun dari huruf-huruf pada kata 'MATEMATIKA' adalah...", ["151.200", "75.600", "302.400", "50.400"], "A", "Permutasi unsur berulang: $\\frac{10!}{2! 3! 2!} = 151.200$.", "**Langkah Penyelesaian Terstruktur:**\\n$$\\frac{3.628.800}{24} = 151.200$$ (Opsi A)."),
    make_q("sma10-b8-18", "Tantangan", "Delegasi 4 orang dipilih dari 6 pria dan 4 wanita. Peluang terpilih sekurang-kurangnya 1 orang wanita adalah...", ["\\frac{13}{14}", "\\frac{1}{14}", "\\frac{11}{14}", "\\frac{5}{7}"], "A", "Komplemen: $1 - \\frac{C(6, 4)}{C(10, 4)} = 1 - \\frac{15}{210} = \\frac{13}{14}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = 1 - \\frac{1}{14} = \\frac{13}{14}$$ (Opsi A)."),
    make_q("sma10-b8-19", "Tantangan", "Dari 4 pasang sepatu (8 sepatu) diambil 2 secara acak. Peluang terambil sepasang sepatu yang cocok adalah...", ["\\frac{1}{7}", "\\frac{1}{8}", "\\frac{1}{14}", "\\frac{2}{7}"], "A", "$P = \\frac{4}{C(8, 2)} = \\frac{4}{28} = \\frac{1}{7}$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{1}{7}$$ (Opsi A)."),
    make_q("sma10-b8-20", "Tantangan", "Dua dadu dilempar bersamaan. Peluang muncul jumlah mata dadu lebih dari 9 atau kelipatan 4 adalah...", ["\\frac{7}{18}", "\\frac{4}{9}", "\\frac{5}{12}", "\\frac{1}{2}"], "A", "$n(> 9) = 6$, $n(\\text{kelipatan 4}) = 9$, irisan $= 1$. Total $(6 + 9 - 1) / 36 = 14 / 36 = 7 / 18$.", "**Langkah Penyelesaian Terstruktur:**\\n$$P = \\frac{14}{36} = \\frac{7}{18}$$ (Opsi A).")
]

# Append
grade10Data["chapters"][0]["questions"].extend(b1_add)
grade10Data["chapters"][1]["questions"].extend(b2_add)
grade10Data["chapters"][2]["questions"].extend(b3_add)
grade10Data["chapters"][3]["questions"].extend(b4_add)
grade10Data["chapters"][4]["questions"].extend(b5_add)
grade10Data["chapters"][5]["questions"].extend(b6_add)
grade10Data["chapters"][6]["questions"].extend(b7_add)
grade10Data["chapters"][7]["questions"].extend(b8_add)

# Verify
for i, ch in enumerate(grade10Data["chapters"]):
    print(f"Bab {i+1} ({ch['id']}): {len(ch['questions'])} questions")

fileContent = f"""/**
 * Data Kurikulum Kelas 10 SMA (Fase E)
 * 8 Bab Wajib Resmi Sesuai Buku Siswa Matematika
 */

export const grade10Data = {json.dumps(grade10Data, indent=2, ensure_ascii=False)};
"""

with open(DATA_PATH, 'w', encoding='utf-8') as f:
    f.write(fileContent)

print("Successfully expanded grade10.js to 20 questions per chapter!")
