import json
import os
import re

DATA_PATH = 'src/data/grades/grade10.js'

with open(DATA_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

json_match = re.search(r'export\s+const\s+\w+\s*=\s*(\{[\s\S]*\});?\s*$', content)
if not json_match:
    raise ValueError("Could not extract grade10Data object")

grade10Data = json.loads(json_match.group(1))

def make_q(q_id, difficulty, question, options_list, correct_key, hint, best_solution):
    return {
        "id": q_id,
        "category": "Latihan",
        "difficulty": difficulty,
        "question": question,
        "options": [
            {"key": "A", "text": options_list[0]},
            {"key": "B", "text": options_list[1]},
            {"key": "C", "text": options_list[2]},
            {"key": "D", "text": options_list[3]}
        ],
        "correctAnswer": correct_key,
        "hint": hint,
        "bestSolution": best_solution
    }

# =========================================================================
# BAB 1: Eksponen dan Logaritma (Existing: 4 -> Add 16 -> Total: 20)
# =========================================================================
b1_add = [
    # Paket 1: Dasar (Soal 5)
    make_q(
        "sma10-b1-5", "Dasar",
        "Nilai dari operasi logaritma $^2\\log 32 - ^2\\log 4$ adalah...",
        ["3", "4", "2", "5"], "A",
        "Gunakan sifat logaritma: $^a\\log b - ^a\\log c = ^a\\log \\left(\\frac{b}{c}\\right)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$^2\\log 32 - ^2\\log 4 = ^2\\log \\left(\\frac{32}{4}\\right) = ^2\\log 8 = 3$$\nNilainya adalah **3** (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b1-6", "Sedang"",
        "Bentuk sederhana dari $\\frac{(x^2 y^{-3})^2}{x^{-1} y^2}$ adalah...",
        ["\\frac{x^5}{y^8}", "\\frac{x^3}{y^8}", "x^5 y^4", "\\frac{x^4}{y^6}"], "A",
        "Pangkatkan masing-masing suku di dalam kurung: $(x^2)^2 = x^4$, $(y^{-3})^2 = y^{-6}$, lalu kurangkan dengan eksponen penyebut.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{x^4 y^{-6}}{x^{-1} y^2} = x^{4 - (-1)} y^{-6 - 2} = x^5 y^{-8} = \\frac{x^5}{y^8}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-7", "Sedang"",
        "Himpunan penyelesaian dari persamaan eksponen $2^{3x - 1} = 32$ adalah...",
        ["{2}", "{3}", "{1}", "{\\frac{5}{3}}"], "A",
        "Samakan basis kedua ruas dengan mengubah 32 menjadi $2^5$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$2^{3x - 1} = 2^5 \\implies 3x - 1 = 5 \\implies 3x = 6 \\implies x = 2$$\nPenyelesaiannya adalah **{2}** (Opsi A)."\n),\nmake_q(\n"sma10-b1-8", "Sedang"",
        "Jika $^3\\log 2 = a$, maka nilai dari $^3\\log 12$ dinyatakan dalam $a$ adalah...",
        ["2a + 1", "a + 2", "2a + 2", "a + 1"], "A",
        "Faktorkan numerus: $12 = 4 \\times 3 = 2^2 \\times 3$, lalu gunakan sifat penjumlahan logaritma.",
        "**Langkah Penyelesaian Terstruktur:**\n$$^3\\log 12 = ^3\\log (2^2 \\times 3) = ^3\\log (2^2) + ^3\\log 3 = 2(^3\\log 2) + 1 = 2a + 1$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-9", "Sedang"",
        "Nilai dari operasi $^2\\log 3 \\cdot ^3\\log 5 \\cdot ^5\\log 8$ adalah...",
        ["3", "2", "4", "1"], "A",
        "Gunakan sifat perkalian berantai logaritma: $^a\\log b \\cdot ^b\\log c = ^a\\log c$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$^2\\log 3 \\cdot ^3\\log 5 \\cdot ^5\\log 8 = ^2\\log 8 = ^2\\log (2^3) = 3$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-10", "Sedang"",
        "Bentuk rasional dari $\\frac{6}{\\sqrt{7} - 2}$ adalah...",
        ["2\\sqrt{7} + 4", "2\\sqrt{7} - 4", "\\sqrt{7} + 2", "3\\sqrt{7} + 6"], "A",
        "Kalikan pembilang dan penyebut dengan sekawan penyebut yaitu $(\\sqrt{7} + 2)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{6}{\\sqrt{7} - 2} \\times \\frac{\\sqrt{7} + 2}{\\sqrt{7} + 2} = \\frac{6(\\sqrt{7} + 2)}{7 - 4} = \\frac{6(\\sqrt{7} + 2)}{3} = 2(\\sqrt{7} + 2) = 2\\sqrt{7} + 4$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b1-11", "Sedang"",
        "Penyelesaian dari persamaan eksponen $5^{x^2 - 3x - 4} = 1$ adalah...",
        ["x = 4 atau x = -1", "x = 4 atau x = 1", "x = -4 atau x = 1", "x = 2 atau x = -2"], "A",
        "Ingat bahwa $a^0 = 1$ untuk $a > 0$, sehingga eksponen $x^2 - 3x - 4$ harus bernilai 0.",
        "**Langkah Penyelesaian Terstruktur:**\n$$x^2 - 3x - 4 = 0 \\implies (x - 4)(x + 1) = 0 \\implies x = 4 \\text{ atau } x = -1$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-12", "Sedang"",
        "Suatu modal sebesar Rp10.000.000,00 diinvestasikan dengan bunga majemuk $10\\%$ per tahun. Besar modal tersebut pada akhir tahun ke-3 adalah...",
        ["Rp13.310.000,00", "Rp13.000.000,00", "Rp12.100.000,00", "Rp14.000.000,00"], "A",
        "Gunakan rumus bunga majemuk: $M_n = M_0(1 + i)^n$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$M_3 = 10.000.000 \\times (1 + 0{,}10)^3 = 10.000.000 \\times 1{,}331 = \\text{Rp}13.310.000,00$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-13", "Sedang"",
        "Massa zat radioaktif mula-mula adalah 160 gram. Zat tersebut meluruh menjadi setengahnya setiap 4 jam. Sisa massa zat radioaktif setelah 16 jam adalah...",
        ["10 gram", "20 gram", "5 gram", "15 gram"], "A",
        "Banyak periode peluruhan $n = \\frac{16}{4} = 4$. Rumus: $M = M_0 \\left(\\frac{1}{2}\\right)^n$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$M = 160 \\times \\left(\\frac{1}{2}\\right)^4 = 160 \\times \\frac{1}{16} = 10\\text{ gram}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-14", "Sedang"",
        "Jika $\\log 2 = 0{,}3010$ dan $\\log 3 = 0{,}4771$, maka nilai dari $\\log 18$ adalah...",
        ["1,2552", "1,2792", "1,1542", "1,3012"], "A",
        "Ubah $18 = 2 \\times 3^2$, maka $\\log 18 = \\log 2 + 2 \\log 3$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\log 18 = 0{,}3010 + 2(0{,}4771) = 0{,}3010 + 0{,}9542 = 1{,}2552$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-15", "Sedang"",
        "Himpunan penyelesaian dari $\\log(x + 6) + \\log(x - 3) = 1$ dengan basis 10 adalah...",
        ["{4}", "{4, -7}", "{5}", "{-7}"], "A",
        "Gabungkan ruas kiri: $\\log((x+6)(x-3)) = 1 = \\log 10$. Ingat syarat numerus $x > 3$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(x + 6)(x - 3) = 10 \\implies x^2 + 3x - 18 - 10 = 0 \\implies x^2 + 3x - 28 = 0$\n2. $(x + 7)(x - 4) = 0 \\implies x = 4$ atau $x = -7$\n3. Syarat numerus: $x > 3$. Jadi nilai yang memenuhi hanyalah $x = 4$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b1-16", "Tantangan"",
        "Nilai $x$ yang memenuhi persamaan eksponen $9^x - 4 \\cdot 3^{x+1} + 27 = 0$ adalah...",
        ["x = 1 atau x = 2", "x = 0 atau x = 3", "x = 1 atau x = 3", "x = 2 atau x = 3"], "A",
        "Misalkan $y = 3^x$, sehingga $9^x = y^2$ dan $3^{x+1} = 3y$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $y^2 - 12y + 27 = 0 \\implies (y - 3)(y - 9) = 0$\n2. $y = 3 \\implies 3^x = 3^1 \\implies x = 1$\n3. $y = 9 \\implies 3^x = 3^2 \\implies x = 2$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-17", "Tantangan"",
        "Jika $^2\\log 3 = a$ dan $^3\\log 5 = b$, maka nilai dari $^{15}\\log 20$ dinyatakan dalam $a$ dan $b$ adalah...",
        ["\\frac{2 + ab}{a(1 + b)}", "\\frac{2a + b}{1 + ab}", "\\frac{a + 2b}{a(1 + b)}", "\\frac{2 + a}{a + b}"], "A",
        "Gunakan perubahan basis ke basis 3: $^{15}\\log 20 = \\frac{^3\\log 20}{^3\\log 15}$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $^3\\log 2 = \\frac{1}{a}$ dan $^3\\log 5 = b$\n2. $^{15}\\log 20 = \\frac{^3\\log (2^2 \\times 5)}{^3\\log (3 \\times 5)} = \\frac{2(^3\\log 2) + ^3\\log 5}{1 + ^3\\log 5} = \\frac{\\frac{2}{a} + b}{1 + b} = \\frac{2 + ab}{a(1 + b)}$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-18", "Tantangan"",
        "Penyelesaian dari pertidaksamaan eksponen $\\left(\\frac{1}{3}\\right)^{2x - 1} \\le 27$ adalah...",
        ["x \\ge -1", "x \\le -1", "x \\ge 2", "x \\le 2"], "A",
        "Ubah ke basis yang sama yaitu 3: $3^{-(2x - 1)} \\le 3^3$. Basis $3 > 1$, tanda ketaksamaan tetap.",
        "**Langkah Penyelesaian Terstruktur:**\n$$3^{-2x + 1} \\le 3^3 \\implies -2x + 1 \\le 3 \\implies -2x \\le 2 \\implies x \\ge -1$$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-19", "Tantangan"",
        "Himpunan penyelesaian dari pertidaksamaan logaritma $^2\\log(x - 2) < 3$ adalah...",
        ["2 < x < 10", "x < 10", "x > 2", "2 < x < 8"], "A",
        "Selesaikan pertidaksamaan $x - 2 < 2^3 = 8$ dan perhatikan syarat numerus $x - 2 > 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $x - 2 < 8 \\implies x < 10$\n2. Syarat numerus: $x - 2 > 0 \\implies x > 2$\n3. Irisan kedua syarat: $2 < x < 10$ (Opsi A)."\n),\nmake_q(\n"sma10-b1-20", "Tantangan"",
        "Jumlah semua nilai $x$ yang memenuhi persamaan logaritma $(^x\\log 2)^2 - 3(^x\\log 2) + 2 = 0$ adalah...",
        ["2 + \\sqrt{2}", "6", "4", "3"], "A",
        "Misalkan $y = ^x\\log 2$. Selesaikan persamaan kuadrat untuk $y$, lalu tentukan $x$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(y - 1)(y - 2) = 0 \\implies y = 1$ atau $y = 2$\n2. $y = 1 \\implies ^x\\log 2 = 1 \\implies x^1 = 2 \\implies x = 2$\n3. $y = 2 \\implies ^x\\log 2 = 2 \\implies x^2 = 2 \\implies x = \\sqrt{2}$ (karena basis $x > 0$ dan $x \\neq 1$)\n4. Jumlah nilai $x = 2 + \\sqrt{2}$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 2: Barisan dan Deret (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb2_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b2-5", "Dasar"",
        "Suku ke-15 dari barisan aritmetika 3, 7, 11, 15, ... adalah...",
        ["59", "63", "55", "61"], "A",
        "Gunakan rumus $U_n = a + (n - 1)b$ dengan suku awal $a = 3$ dan beda $b = 4$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$U_{15} = 3 + (15 - 1) \\times 4 = 3 + 56 = 59$$\nSuku ke-15 adalah **59** (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b2-6", "Sedang"",
        "Jumlah 20 suku pertama ($S_{20}$) dari deret aritmetika $4 + 7 + 10 + 13 + \\dots$ adalah...",
        ["650", "620", "680", "640"], "A",
        "Gunakan rumus jumlah deret aritmetika: $S_n = \\frac{n}{2}(2a + (n - 1)b)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$S_{20} = \\frac{20}{2}(2(4) + (20 - 1)3) = 10(8 + 57) = 10 \\times 65 = 650$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-7", "Sedang"",
        "Suku ke-7 dari barisan geometri 2, 6, 18, 54, ... adalah...",
        ["1.458", "486", "4.374", "729"], "A",
        "Rumus suku ke-$n$ geometri: $U_n = a r^{n-1}$ dengan $a = 2$ dan rasio $r = 3$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$U_7 = 2 \\times 3^{7 - 1} = 2 \\times 3^6 = 2 \\times 729 = 1.458$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-8", "Sedang"",
        "Jumlah deret geometri tak hingga $18 + 6 + 2 + \\frac{2}{3} + \\dots$ adalah...",
        ["27", "24", "36", "18"], "A",
        "Rasio $r = \\frac{6}{18} = \\frac{1}{3}$. Gunakan rumus $S_\\infty = \\frac{a}{1 - r}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$S_\\infty = \\frac{18}{1 - \\frac{1}{3}} = \\frac{18}{\\frac{2}{3}} = 18 \\times \\frac{3}{2} = 27$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-9", "Sedang"",
        "Dari suatu barisan aritmetika diketahui suku ke-3 adalah 11 dan suku ke-8 adalah 26. Suku pertama ($a$) dan beda ($b$) barisan tersebut berturut-turut adalah...",
        ["5 dan 3", "3 dan 5", "2 dan 4", "4 dan 3"], "A",
        "Eliminasi beda $b$ dari selisih suku: $U_8 - U_3 = 5b = 26 - 11 = 15$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $5b = 15 \\implies b = 3$\n2. $U_3 = a + 2(3) = 11 \\implies a = 5$\nSuku pertama 5 dan beda 3 (Opsi A)."\n),\nmake_q(\n"sma10-b2-10", "Sedang"",
        "Banyaknya suku pada barisan aritmetika 5, 9, 13, 17, ..., 121 adalah...",
        ["30", "29", "31", "28"], "A",
        "Gunakan rumus $U_n = a + (n - 1)b = 121$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$5 + (n - 1)4 = 121 \\implies 4(n - 1) = 116 \\implies n - 1 = 29 \\implies n = 30$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b2-11", "Sedang"",
        "Sebuah bola dijatuhkan dari ketinggian 12 meter dan memantul kembali dengan ketinggian $\\frac{2}{3}$ kali tinggi sebelumnya hingga berhenti. Panjang lintasan seluruh pantulan bola adalah...",
        ["60 meter", "48 meter", "72 meter", "36 meter"], "A",
        "Rumus praktis pantulan bola dengan rasio $\\frac{a}{b}$: $S = h \\times \\frac{b + a}{b - a}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$S = 12 \\times \\frac{3 + 2}{3 - 2} = 12 \\times 5 = 60\\text{ meter}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-12", "Sedang"",
        "Di dalam sebuah gedung pertunjukan, baris paling depan memiliki 15 kursi. Setiap baris di belakangnya selalu memuat 3 kursi lebih banyak dari baris di depannya. Jika terdapat 12 baris kursi di gedung tersebut, kapasitas total penonton adalah...",
        ["378 kursi", "360 kursi", "396 kursi", "350 kursi"], "A",
        "Total kursi adalah deret aritmetika $S_{12}$ dengan $a = 15, b = 3, n = 12$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$S_{12} = \\frac{12}{2}(2(15) + (12 - 1)3) = 6(30 + 33) = 6 \\times 63 = 378\\text{ kursi}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-13", "Sedang"",
        "Gaji seorang karyawan dinaikkan sebesar Rp200.000,00 secara tetap setiap tahunnya. Jika gaji mula-mula pada tahun pertama adalah Rp4.000.000,00 per bulan, total gaji yang diterima karyawan tersebut selama 5 tahun bekerja (asumsi per bulan tetap tiap tahun) adalah...",
        ["Rp264.000.000,00", "Rp240.000.000,00", "Rp250.000.000,00", "Rp275.000.000,00"], "A",
        "Rata-rata gaji tahunan $= 12 \\times \\text{gaji bulanan}$. Total 5 tahun $= 12 \\times S_5$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $S_5 = \\frac{5}{2}(2(4.000.000) + 4(200.000)) = \\frac{5}{2}(8.000.000 + 800.000) = 22.000.000$\n2. Total gaji $= 12 \\times 22.000.000 = \\text{Rp}264.000.000,00$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-14", "Sedang"",
        "Tiga buah bilangan membentuk barisan geometri. Jumlah ketiga bilangan tersebut adalah 26 dan hasil kalinya adalah 216. Suku kedua (tengah) dari barisan tersebut adalah...",
        ["6", "8", "4", "9"], "A",
        "Misalkan tiga bilangan itu $\\frac{a}{r}, a, ar$. Hasil kalinya adalah $a^3 = 216$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$a^3 = 216 \\implies a = 6$$\nSuku tengah barisan geometri tersebut adalah **6** (Opsi A)."\n),\nmake_q(\n"sma10-b2-15", "Sedang"",
        "Jumlah $n$ suku pertama suatu deret aritmetika ditentukan oleh rumus $S_n = 2n^2 + 3n$. Suku ke-8 ($U_8$) dari deret tersebut adalah...",
        ["33", "35", "31", "37"], "A",
        "Gunakan hubungan $U_n = S_n - S_{n-1}$ atau cari turunan formula beda.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $S_8 = 2(8^2) + 3(8) = 2(64) + 24 = 152$\n2. $S_7 = 2(7^2) + 3(7) = 2(49) + 21 = 119$\n3. $U_8 = 152 - 119 = 33$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b2-16", "Tantangan"",
        "Antara bilangan 3 dan 48 disisipkan 3 buah bilangan sehingga terbentuk barisan geometri baru. Rasio dari barisan geometri baru tersebut adalah...",
        ["2", "3", "4", "1,5"], "A",
        "Rumus rasio sisipan geometri: $r' = \\sqrt[k+1]{\\frac{b}{a}}$ dengan $k = 3$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$r' = \\sqrt[3+1]{\\frac{48}{3}} = \\sqrt[4]{16} = 2$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-17", "Tantangan"",
        "Jumlah suku-suku nomor ganjil dari suatu deret geometri tak hingga adalah 18, sedangkan jumlah seluruh suku tak hingganya adalah 24. Rasio dari deret geometri tersebut adalah...",
        ["\\frac{1}{3}", "\\frac{1}{2}", "\\frac{1}{4}", "\\frac{2}{3}"], "A",
        "Deret ganjil: $S_{\\text{ganjil}} = \\frac{a}{1 - r^2}$. Deret total: $S = \\frac{a}{1 - r}$. Bagi kedua persamaan.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{S_{\\text{ganjil}}}{S} = \\frac{1 - r}{1 - r^2} = \\frac{1}{1 + r} = \\frac{18}{24} = \\frac{3}{4} \\implies 3(1 + r) = 4 \\implies r = \\frac{1}{3}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-18", "Tantangan"",
        "Sebuah tali dipotong menjadi 6 bagian yang panjangnya membentuk barisan geometri. Jika panjang tali terpendek 3 cm dan potongan terpanjang 96 cm, maka panjang tali mula-mula adalah...",
        ["189 cm", "192 cm", "186 cm", "195 cm"], "A",
        "Tali terpendek $a = 3$, terpanjang $U_6 = 96 \\implies 3 r^5 = 96 \\implies r^5 = 32 \\implies r = 2$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$S_6 = \\frac{3(2^6 - 1)}{2 - 1} = 3(64 - 1) = 3 \\times 63 = 189\\text{ cm}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b2-19", "Tantangan"",
        "Jika $(k - 2), (k + 1), (2k + 2)$ merupakan tiga suku berurutan dari suatu barisan geometri dengan rasio positif, maka nilai dari $k$ adalah...",
        ["5", "4", "3", "6"], "A",
        "Syarat suku berurutan geometri: $(U_2)^2 = U_1 \times U_3$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(k + 1)^2 = (k - 2)(2k + 2)\n2. $k^2 + 2k + 1 = 2k^2 - 2k - 4 \\implies k^2 - 4k - 5 = 0$\n3. $(k - 5)(k + 1) = 0 \\implies k = 5$ (karena suku positif) (Opsi A)."\n),\nmake_q(\n"sma10-b2-20", "Tantangan"",
        "Jumlah 10 suku pertama dari deret $1 \\cdot 2 + 2 \\cdot 3 + 3 \\cdot 4 + \\dots + 10 \\cdot 11$ adalah...",
        ["440", "420", "460", "400"], "A",
        "Rumus suku ke-$n$ adalah $U_n = n(n + 1) = n^2 + n$. Jumlah deret $= \\sum n^2 + \\sum n$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\sum_{n=1}^{10} n^2 = \\frac{10 \\times 11 \\times 21}{6} = 385$\n2. $\\sum_{n=1}^{10} n = \\frac{10 \\times 11}{2} = 55$\n3. Total $= 385 + 55 = 440$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 3: Vektor dan Operasinya (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb3_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b3-5", "Dasar"",
        "Panjang (besar) dari vektor $\\vec{v} = \\begin{pmatrix} 6 \\\\ -8 \\end{pmatrix}$ adalah...",
        ["10", "14", "12", "8"], "A",
        "Gunakan rumus panjang vektor: $|\\vec{v}| = \\sqrt{x^2 + y^2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$|\\vec{v}| = \\sqrt{6^2 + (-8)^2} = \\sqrt{36 + 64} = \\sqrt{100} = 10$$\nPanjang vektornya adalah **10** (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b3-6", "Sedang"",
        "Diketahui vektor $\\vec{a} = 3\\vec{i} - 2\\vec{j}$ dan $\\vec{b} = -\\vec{i} + 5\\vec{j}$. Hasil dari $2\\vec{a} + 3\\vec{b}$ adalah...",
        ["3\\vec{i} + 11\\vec{j}", "5\\vec{i} + 11\\vec{j}", "3\\vec{i} + 9\\vec{j}", "4\\vec{i} + 11\\vec{j}"], "A",
        "Kalikan masing-masing komponen vektor dengan skalarnya lalu jumlahkan.",
        "**Langkah Penyelesaian Terstruktur:**\n$$2(3\\vec{i} - 2\\vec{j}) + 3(-\\vec{i} + 5\\vec{j}) = (6\\vec{i} - 4\\vec{j}) + (-3\\vec{i} + 15\\vec{j}) = 3\\vec{i} + 11\\vec{j}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-7", "Sedang"",
        "Jika titik $A(2, -3)$ dan $B(7, 9)$, maka vektor $\\vec{AB}$ adalah...",
        ["\\begin{pmatrix} 5 \\\\ 12 \\end{pmatrix}", "\\begin{pmatrix} 9 \\\\ 6 \\end{pmatrix}", "\\begin{pmatrix} -5 \\\\ -12 \\end{pmatrix}", "\\begin{pmatrix} 5 \\\\ 6 \\end{pmatrix}"], "A",
        "Vektor $\\vec{AB} = B - A = \\begin{pmatrix} x_B - x_A \\\\ y_B - y_A \\end{pmatrix}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\vec{AB} = \\begin{pmatrix} 7 - 2 \\\\ 9 - (-3) \\end{pmatrix} = \\begin{pmatrix} 5 \\\\ 12 \\end{pmatrix}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-8", "Sedang"",
        "Hasil perkalian skalar (dot product) antara vektor $\\vec{u} = \\begin{pmatrix} 4 \\\\ -2 \\\\ 5 \\end{pmatrix}$ dan $\\vec{v} = \\begin{pmatrix} 3 \\\\ 6 \\\\ 1 \\end{pmatrix}$ adalah...",
        ["5", "9", "7", "3"], "A",
        "Rumus perkalian skalar: $\\vec{u} \\cdot \\vec{v} = x_1 x_2 + y_1 y_2 + z_1 z_2$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\vec{u} \\cdot \\vec{v} = (4 \\times 3) + (-2 \\times 6) + (5 \\times 1) = 12 - 12 + 5 = 5$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-9", "Sedang"",
        "Vektor satuan yang searah dengan vektor $\\vec{a} = \\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix}$ adalah...",
        ["\\begin{pmatrix} \\frac{3}{5} \\\\ \\frac{4}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{4}{5} \\\\ \\frac{3}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{3}{7} \\\\ \\frac{4}{7} \\end{pmatrix}", "\\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}"], "A",
        "Vektor satuan dirumuskan $\\vec{e} = \\frac{\\vec{a}}{|\\vec{a}|}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$|\\vec{a}| = \\sqrt{3^2 + 4^2} = 5 \\implies \\vec{e} = \\begin{pmatrix} \\frac{3}{5} \\\\ \\frac{4}{5} \\end{pmatrix}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-10", "Sedang"",
        "Dua buah vektor $\\vec{p} = \\begin{pmatrix} x \\\\ 4 \\end{pmatrix}$ dan $\\vec{q} = \\begin{pmatrix} 6 \\\\ -3 \\end{pmatrix}$ saling tegak lurus (ortogonal). Nilai dari $x$ adalah...",
        ["2", "3", "-2", "4"], "A",
        "Dua vektor saling tegak lurus jika hasil kali titiknya sama dengan nol: $\\vec{p} \\cdot \\vec{q} = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$x(6) + 4(-3) = 0 \\implies 6x - 12 = 0 \\implies x = 2$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b3-11", "Sedang"",
        "Besar sudut antara dua vektor $\\vec{a} = \\begin{pmatrix} 1 \\\\ 0 \\end{pmatrix}$ dan $\\vec{b} = \\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}$ adalah...",
        ["45^\\circ", "30^\\circ", "60^\\circ", "90^\\circ"], "A",
        "Gunakan rumus kosinus sudut antara dua vektor: $\\cos \\theta = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{a}||\\vec{b}|}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos \\theta = \\frac{1(1) + 0(1)}{\\sqrt{1} \\times \\sqrt{2}} = \\frac{1}{\\sqrt{2}} = \\frac{1}{2}\\sqrt{2} \\implies \\theta = 45^\\circ$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-12", "Sedang"",
        "Panjang proyeksi skalar ortogonal vektor $\\vec{u} = \\begin{pmatrix} 2 \\\\ 4 \\end{pmatrix}$ pada arah vektor $\\vec{v} = \\begin{pmatrix} 3 \\\\ 4 \\end{pmatrix}$ adalah...",
        ["\\frac{22}{5}", "4", "\\frac{24}{5}", "5"], "A",
        "Rumus proyeksi skalar: $|\\vec{c}| = \\frac{\\vec{u} \\cdot \\vec{v}}{|\\vec{v}|}$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\vec{u} \\cdot \\vec{v} = 2(3) + 4(4) = 6 + 16 = 22$\n2. $|\\vec{v}| = \\sqrt{3^2 + 4^2} = 5$\n3. Proyeksi skalar $= \\frac{22}{5}$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-13", "Sedang"",
        "Titik $M$ membagi ruas garis $AB$ dengan perbandingan $AM : MB = 2 : 1$. Jika $A(1, 4)$ dan $B(7, 10)$, koordinat titik $M$ adalah...",
        ["(5, 8)", "(4, 7)", "(5, 7)", "(6, 8)"], "A",
        "Gunakan rumus pembagian ruas garis: $M = \\frac{mB + nA}{m + n}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$M = \\frac{2(7, 10) + 1(1, 4)}{2 + 1} = \\frac{(14+1, 20+4)}{3} = \\left(\\frac{15}{3}, \\frac{24}{3}\\right) = (5, 8)$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-14", "Sedang"",
        "Sebuah perahu menyeberangi sungai dengan kecepatan $8\\text{ m/s}$ tegak lurus arus air. Jika kecepatan arus sungai adalah $6\\text{ m/s}$, maka kecepatan resultan perahu tersebut adalah...",
        ["10 m/s", "14 m/s", "12 m/s", "9 m/s"], "A",
        "Karena arahnya saling tegak lurus, gunakan resultan vektor Pythagoras: $v = \\sqrt{v_x^2 + v_y^2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$v = \\sqrt{8^2 + 6^2} = \\sqrt{64 + 36} = \\sqrt{100} = 10\\text{ m/s}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-15", "Sedang"",
        "Diketahui $|\\vec{a}| = 4$, $|\\vec{b}| = 6$, dan sudut antara keduanya adalah $60^\\circ$. Nilai dari perkalian skalar $\\vec{a} \\cdot \\vec{b}$ adalah...",
        ["12", "12\\sqrt{3}", "24", "18"], "A",
        "Rumus: $\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}| \\cos 60^\\circ$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\vec{a} \\cdot \\vec{b} = 4 \\times 6 \\times \\cos 60^\\circ = 24 \\times \\frac{1}{2} = 12$$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b3-16", "Tantangan"",
        "Jika $|\\vec{u}| = 5$, $|\\vec{v}| = 3$, dan $|\\vec{u} - \\vec{v}| = 7$, maka nilai dari $|\\vec{u} + \\vec{v}|$ adalah...",
        ["\\sqrt{19}", "5", "4\\sqrt{2}", "\\sqrt{21}"], "A",
        "Gunakan identitas jajar genjang: $|\\vec{u} + \\vec{v}|^2 + |\\vec{u} - \\vec{v}|^2 = 2(|\\vec{u}|^2 + |\\vec{v}|^2)$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $|\\vec{u} + \\vec{v}|^2 + 7^2 = 2(5^2 + 3^2) = 2(25 + 9) = 68$\n2. $|\\vec{u} + \\vec{v}|^2 = 68 - 49 = 19 \\implies |\\vec{u} + \\vec{v}| = \\sqrt{19}$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-17", "Tantangan"",
        "Vektor proyeksi ortogonal dari $\\vec{a} = \\begin{pmatrix} 1 \\\\ 2 \\end{pmatrix}$ pada vektor $\\vec{b} = \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix}$ adalah...",
        ["\\begin{pmatrix} \\frac{8}{5} \\\\ \\frac{4}{5} \\end{pmatrix}", "\\begin{pmatrix} \\frac{4}{5} \\\\ \\frac{8}{5} \\end{pmatrix}", "\\begin{pmatrix} 1 \\\\ 1 \\end{pmatrix}", "\\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix}"], "A",
        "Rumus vektor proyeksi ortogonal: $\\vec{p} = \\frac{\\vec{a} \\cdot \\vec{b}}{|\\vec{b}|^2} \\vec{b}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\vec{p} = \\frac{1(2) + 2(1)}{2^2 + 1^2} \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix} = \\frac{4}{5} \\begin{pmatrix} 2 \\\\ 1 \\end{pmatrix} = \\begin{pmatrix} \\frac{8}{5} \\\\ \\frac{4}{5} \\end{pmatrix}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-18", "Tantangan"",
        "Titik $A(1, 2, 3)$, $B(2, 4, 5)$, dan $C(x, 8, y)$ terletak pada satu garis lurus (kolinier). Nilai dari $x + y$ adalah...",
        ["13", "14", "12", "15"], "A",
        "Syarat segaris: $\\vec{AB} = k \\vec{AC}$ atau $\\vec{BC} = k \\vec{AB}$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\vec{AB} = (1, 2, 2)$\n2. $\\vec{BC} = (x - 2, 8 - 4, y - 5) = (x - 2, 4, y - 5)$\n3. Rasio komponen $y$: $k = \\frac{4}{2} = 2$\n4. $x - 2 = 2(1) \\implies x = 4$\n5. $y - 5 = 2(2) \\implies y = 9$\n6. $x + y = 4 + 9 = 13$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-19", "Tantangan"",
        "Diketahui segitiga $ABC$ dengan $\\vec{AB} = \\vec{u}$ dan $\\vec{AC} = \\vec{v}$. Jika titik $D$ adalah titik tengah $BC$, maka vektor $\\vec{AD}$ dinyatakan dalam $\\vec{u}$ dan $\\vec{v}$ adalah...",
        ["\\frac{1}{2}(\\vec{u} + \\vec{v})", "\\frac{1}{2}(\\vec{u} - \\vec{v})", "\\vec{u} + \\frac{1}{2}\\vec{v}", "\\frac{1}{2}\\vec{u} + \\vec{v}"], "A",
        "Titik tengah sisi segitiga memiliki vektor posisi rata-rata dari kedua titik sudutnya.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\vec{AD} = \\frac{\\vec{AB} + \\vec{AC}}{2} = \\frac{1}{2}(\\vec{u} + \\vec{v})$$ (Opsi A)."\n),\nmake_q(\n"sma10-b3-20", "Tantangan"",
        "Tiga buah gaya $F_1 = 10\\text{ N}$ searah sumbu X positif, $F_2 = 10\\text{ N}$ berarah $60^\\circ$ terhadap sumbu X positif, dan $F_3$ bekerja pada sebuah benda hingga benda berada dalam keadaan setimbang (resultan gaya nol). Besar gaya $F_3$ adalah...",
        ["10\\sqrt{3}\\text{ N}", "15\\text{ N}", "20\\text{ N}", "10\\sqrt{2}\\text{ N}"], "A",
        "Hitung komponen resultan $R_x = 10 + 10\\cos 60^\\circ = 15$ dan $R_y = 10\\sin 60^\\circ = 5\\sqrt{3}$. Besar $F_3 = \\sqrt{R_x^2 + R_y^2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$|F_3| = \\sqrt{15^2 + (5\\sqrt{3})^2} = \\sqrt{225 + 75} = \\sqrt{300} = 10\\sqrt{3}\\text{ N}$$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 4: Trigonometri (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb4_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b4-5", "Dasar"",
        "Nilai dari $\\cos 60^\\circ + \\sin 30^\\circ$ adalah...",
        ["1", "\\frac{1}{2}\\sqrt{3}", "\\frac{1}{2}", "\\sqrt{3}"], "A",
        "Ingat tabel perbandingan trigonometri sudut istimewa: $\\cos 60^\\circ = \\frac{1}{2}$ dan $\\sin 30^\\circ = \\frac{1}{2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos 60^\\circ + \\sin 30^\\circ = \\frac{1}{2} + \\frac{1}{2} = 1$$ (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b4-6", "Sedang"",
        "Jika $\\sin A = \\frac{3}{5}$ dengan $A$ sudut lancip, maka nilai dari $\\tan A$ adalah...",
        ["\\frac{3}{4}", "\\frac{4}{3}", "\\frac{4}{5}", "\\frac{3}{5}"], "A",
        "Sisi depan $= 3$, sisi miring $= 5$. Cari sisi samping dengan tripel Pythagoras ($4$).",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\text{samping} = \\sqrt{5^2 - 3^2} = 4 \\implies \\tan A = \\frac{\\text{depan}}{\\text{samping}} = \\frac{3}{4}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-7", "Sedang"",
        "Nilai dari $\\sin 150^\\circ$ adalah...",
        ["\\frac{1}{2}", "-\\frac{1}{2}", "\\frac{1}{2}\\sqrt{3}", "-\\frac{1}{2}\\sqrt{3}"], "A",
        "Sudut $150^\\circ$ berada di Kuadran II di mana nilai sinus bernilai positif: $\\sin(180^\\circ - 30^\\circ) = \\sin 30^\\circ$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\sin 150^\\circ = \\sin(180^\\circ - 30^\\circ) = \\sin 30^\\circ = \\frac{1}{2}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-8", "Sedang"",
        "Nilai dari $\\cos 240^\\circ$ adalah...",
        ["-\\frac{1}{2}", "\\frac{1}{2}", "-\\frac{1}{2}\\sqrt{3}", "\\frac{1}{2}\\sqrt{3}"], "A",
        "Sudut $240^\\circ$ berada di Kuadran III: $\\cos(180^\\circ + 60^\\circ) = -\\cos 60^\\circ$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos 240^\\circ = -\\cos 60^\\circ = -\\frac{1}{2}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-9", "Sedang"",
        "Bentuk sederhana dari $(1 - \\sin^2 \\theta)(1 + \\tan^2 \\theta)$ adalah...",
        ["1", "\\cos^2 \\theta", "\\sin^2 \\theta", "\\tan^2 \\theta"], "A",
        "Gunakan identitas trigonometri: $1 - \\sin^2 \\theta = \\cos^2 \\theta$ dan $1 + \\tan^2 \\theta = \\sec^2 \\theta = \\frac{1}{\\cos^2 \\theta}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos^2 \\theta \\times \\frac{1}{\\cos^2 \\theta} = 1$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-10", "Sedang"",
        "Seorang pengamat melihat puncak menara dengan sudut elevasi $45^\\circ$. Jika jarak horizontal pengamat ke dasar menara adalah 30 meter dan tinggi pengamat diabaikan, tinggi menara tersebut adalah...",
        ["30 meter", "30\\sqrt{3} meter", "15 meter", "15\\sqrt{2} meter"], "A",
        "Gunakan perbandingan tangen: $\\tan 45^\\circ = \\frac{\\text{tinggi}}{\\text{jarak}}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\tan 45^\\circ = \\frac{t}{30} \\implies 1 = \\frac{t}{30} \\implies t = 30\\text{ meter}$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b4-11", "Sedang"",
        "Pada segitiga $ABC$, diketahui panjang sisi $a = 6\\text{ cm}$, sudut $A = 30^\\circ$, dan sudut $B = 45^\\circ$. Panjang sisi $b$ adalah...",
        ["6\\sqrt{2}\\text{ cm}", "3\\sqrt{2}\\text{ cm}", "6\\sqrt{3}\\text{ cm}", "4\\sqrt{2}\\text{ cm}"], "A",
        "Gunakan aturan sinus: $\\frac{a}{\\sin A} = \\frac{b}{\\sin B}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{6}{\\sin 30^\\circ} = \\frac{b}{\\sin 45^\\circ} \\implies \\frac{6}{\\frac{1}{2}} = \\frac{b}{\\frac{1}{2}\\sqrt{2}} \\implies 12 = \\frac{b}{\\frac{1}{2}\\sqrt{2}} \\implies b = 6\\sqrt{2}\\text{ cm}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-12", "Sedang"",
        "Pada segitiga $ABC$, diketahui panjang $b = 5\\text{ cm}$, $c = 8\\text{ cm}$, dan sudut $A = 60^\\circ$. Panjang sisi $a$ adalah...",
        ["7 cm", "8 cm", "6 cm", "\\sqrt{53} cm"], "A",
        "Gunakan aturan cosinus: $a^2 = b^2 + c^2 - 2bc\\cos A$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$a^2 = 5^2 + 8^2 - 2(5)(8)\\cos 60^\\circ = 25 + 64 - 80\\left(\\frac{1}{2}\\right) = 89 - 40 = 49$$\n$$a = \\sqrt{49} = 7\\text{ cm}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-13", "Sedang"",
        "Luas segitiga $PQR$ dengan panjang sisi $p = 10\\text{ cm}$, $q = 12\\text{ cm}$, dan sudut $R = 30^\\circ$ adalah...",
        ["30 cm^2", "60 cm^2", "30\\sqrt{3} cm^2", "45 cm^2"], "A",
        "Rumus luas segitiga trigonometri: $L = \\frac{1}{2} p q \\sin R$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$L = \\frac{1}{2} \\times 10 \\times 12 \\times \\sin 30^\\circ = 60 \\times \\frac{1}{2} = 30\\text{ cm}^2$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-14", "Sedang"",
        "Jika $\\tan \\alpha = -\\frac{4}{3}$ dan $\\alpha$ berada di kuadran II, maka nilai dari $\\cos \\alpha$ adalah...",
        ["-\\frac{3}{5}", "\\frac{3}{5}", "-\\frac{4}{5}", "\\frac{4}{5}"], "A",
        "Di Kuadran II, cosinus bernilai negatif. Samping $= 3$, miring $= 5$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos \\alpha = -\\frac{\\text{samping}}{\\text{miring}} = -\\frac{3}{5}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-15", "Sedang"",
        "Nilai dari $\\frac{\\sin 120^\\circ \\cdot \\cos 300^\\circ}{\\tan 225^\\circ}$ adalah...",
        ["\\frac{1}{4}\\sqrt{3}", "\\frac{1}{2}\\sqrt{3}", "\\frac{1}{4}", "\\frac{1}{2}"], "A",
        "Hitung masing-masing nilai: $\\sin 120^\\circ = \\frac{1}{2}\\sqrt{3}$, $\\cos 300^\\circ = \\frac{1}{2}$, $\\tan 225^\\circ = 1$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{\\frac{1}{2}\\sqrt{3} \\times \\frac{1}{2}}{1} = \\frac{1}{4}\\sqrt{3}$$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b4-16", "Tantangan"",
        "Sebuah kapal berlayar dari pelabuhan $A$ ke arah $060^\\circ$ sejauh 20 mil laut menuju pelabuhan $B$. Kemudian berbelok ke arah $120^\\circ$ sejauh 20 mil laut menuju pelabuhan $C$. Jarak pelabuhan $A$ ke pelabuhan $C$ adalah...",
        ["20\\sqrt{3} mil laut", "20 mil laut", "40 mil laut", "30 mil laut"], "A",
        "Sudut apit pada titik $B$ adalah $180^\\circ - (120^\\circ - 60^\\circ) = 120^\\circ$. Gunakan aturan cosinus.",
        "**Langkah Penyelesaian Terstruktur:**\n$$AC^2 = 20^2 + 20^2 - 2(20)(20)\\cos 120^\\circ = 800 - 800\\left(-\\frac{1}{2}\\right) = 800 + 400 = 1.200$$\n$$AC = \\sqrt{1.200} = 20\\sqrt{3}\\text{ mil laut}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-17", "Tantangan"",
        "Bentuk sederhana dari $\\frac{\\sin x}{1 + \\cos x} + \\frac{1 + \\cos x}{\\sin x}$ adalah...",
        ["2\\csc x", "2\\sec x", "2\\tan x", "\\csc x"], "A",
        "Samakan penyebut kedua pecahan: penyebut $(1 + \\cos x)\\sin x$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{\\sin^2 x + (1 + \\cos x)^2}{(1 + \\cos x)\\sin x} = \\frac{\\sin^2 x + 1 + 2\\cos x + \\cos^2 x}{(1 + \\cos x)\\sin x} = \\frac{2 + 2\\cos x}{(1 + \\cos x)\\sin x} = \\frac{2(1 + \\cos x)}{(1 + \\cos x)\\sin x} = 2\\csc x$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-18", "Tantangan"",
        "Himpunan penyelesaian persamaan trigonometri $2\\sin x - \\sqrt{3} = 0$ untuk interval $0^\\circ \\le x \\le 360^\\circ$ adalah...",
        ["{60^\\circ, 120^\\circ}", "{30^\\circ, 150^\\circ}", "{60^\\circ, 240^\\circ}", "{60^\\circ, 300^\\circ}"], "A",
        "$\\sin x = \\frac{1}{2}\\sqrt{3}$. Nilai positif sinus ada di Kuadran I dan Kuadran II.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Kuadran I: $x = 60^\\circ$\n2. Kuadran II: $x = 180^\\circ - 60^\\circ = 120^\\circ$\nPenyelesaiannya adalah **{60^\\circ, 120^\\circ}** (Opsi A)."\n),\nmake_q(\n"sma10-b4-19", "Tantangan"",
        "Panjang sisi-sisi suatu segitiga adalah 5 cm, 6 cm, dan 7 cm. Nilai kosinus sudut terbesar segitiga tersebut adalah...",
        ["\\frac{1}{5}", "\\frac{2}{5}", "\\frac{1}{7}", "\\frac{1}{6}"], "A",
        "Sudut terbesar berada di hadapan sisi terpanjang ($c = 7$). Gunakan aturan cosinus: $\\cos C = \\frac{a^2 + b^2 - c^2}{2ab}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\cos C = \\frac{5^2 + 6^2 - 7^2}{2(5)(6)} = \\frac{25 + 36 - 49}{60} = \\frac{12}{60} = \\frac{1}{5}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b4-20", "Tantangan"",
        "Nilai dari $\\sin^2 15^\\circ + \\sin^2 75^\\circ$ adalah...",
        ["1", "\\frac{1}{2}", "\\frac{1}{2}\\sqrt{3}", "2"], "A",
        "Gunakan relasi sudut komplementer: $\\sin 75^\\circ = \\cos(90^\\circ - 75^\\circ) = \\cos 15^\\circ$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\sin^2 15^\\circ + \\cos^2 15^\\circ = 1$$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 5: SPLTV dan SPtLDV (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb5_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b5-5", "Dasar"",
        "Titik berikut yang berada di dalam daerah penyelesaian pertidaksamaan $2x + 3y \\le 12$ adalah...",
        ["(1, 2)", "(4, 3)", "(5, 2)", "(3, 4)"], "A",
        "Uji titik $(1, 2)$ dengan memasukkannya ke dalam pertidaksamaan: $2(1) + 3(2) = 8 \\le 12$ (benar).",
        "**Langkah Penyelesaian Terstruktur:**\n$$2(1) + 3(2) = 2 + 6 = 8 \\le 12$$\nTitik **(1, 2)** memenuhi pertidaksamaan (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b5-6", "Sedang"",
        "Diketahui SPLTV $\begin{cases} x + y + z = 6 \\ x + 2y + z = 8 \\ 2x - y + z = 3 \end{cases}$. Nilai dari $x$ adalah...",
        ["1", "2", "3", "4"], "A",
        "Kurangkan persamaan 2 dengan persamaan 1 untuk menemukan nilai $y$, lalu selesaikan untuk $x$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(x + 2y + z) - (x + y + z) = 8 - 6 \implies y = 2$\n2. Dari pers 1: $x + z = 4$\n3. Dari pers 3: $2x - 2 + z = 3 \implies 2x + z = 5$\n4. $(2x + z) - (x + z) = 5 - 4 \implies x = 1$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-7", "Sedang"",
        "Harga 2 kg mangga, 1 kg apel, dan 3 kg jeruk adalah Rp87.000,00. Jika $x =$ harga mangga, $y =$ harga apel, dan $z =$ harga jeruk per kg, persamaan linear yang sesuai adalah...",
        ["2x + y + 3z = 87.000", "x + 2y + 3z = 87.000", "3x + y + 2z = 87.000", "2x + 3y + z = 87.000"], "A",
        "Kalikan masing-masing kuantitas buah dengan variabel harga per kilogramnya.",
        "**Langkah Penyelesaian Terstruktur:**\nPersamaan yang tepat: **$2x + y + 3z = 87.000$** (Opsi A)."\n),\nmake_q(\n"sma10-b5-8", "Sedang"",
        "Daerah himpunan penyelesaian dari sistem pertidaksamaan $\\begin{cases} x + y \\ge 4 \\\\ 2x + y \\le 6 \\\\ x \\ge 0, y \\ge 0 \\end{cases}$ terletak pada kuadran...",
        ["Kuadran I", "Kuadran II", "Kuadran III", "Kuadran IV"], "A",
        "Syarat $x \\ge 0$ dan $y \\ge 0$ membatasi daerah hanya pada Kuadran I.",
        "**Langkah Penyelesaian Terstruktur:**\nKarena $x \\ge 0$ dan $y \\ge 0$, seluruh daerah penyelesaian berada di **Kuadran I** (Opsi A)."\n),\nmake_q(\n"sma10-b5-9", "Sedang"",
        "Nilai maksimum dari fungsi objektif $f(x, y) = 3x + 4y$ pada titik-titik pojok $(0, 0)$, $(4, 0)$, $(2, 3)$, dan $(0, 4)$ adalah...",
        ["18", "16", "12", "20"], "A",
        "Uji setiap titik pojok ke fungsi objektif $f(x, y)$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $f(0, 0) = 0$\n2. $f(4, 0) = 12$\n3. $f(2, 3) = 3(2) + 4(3) = 6 + 12 = 18$\n4. $f(0, 4) = 16$\nNilai maksimumnya adalah **18** (Opsi A)."\n),\nmake_q(\n"sma10-b5-10", "Sedang"",
        "Penyelesaian dari pertidaksamaan $3x - 2y < 6$ membagi bidang kartesius menjadi dua bagian. Titik potong garis pembatas dengan sumbu koordinat adalah...",
        ["(2, 0) dan (0, -3)", "(3, 0) dan (0, -2)", "(-2, 0) dan (0, 3)", "(0, 2) dan (-3, 0)"], "A",
        "Garis pembatas adalah $3x - 2y = 6$. Masukkan $y = 0$ dan $x = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Sumbu-X ($y=0$): $3x = 6 \\implies x = 2 \\implies (2, 0)$\n2. Sumbu-Y ($x=0$): $-2y = 6 \\implies y = -3 \\implies (0, -3)$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b5-11", "Sedang"",
        "Tiga bersaudara Ali, Budi, dan Cici memiliki total umur 45 tahun. Umur Budi 2 tahun lebih muda dari Ali, sedangkan umur Cici 5 tahun lebih muda dari Budi. Umur Ali adalah...",
        ["18 tahun", "16 tahun", "15 tahun", "20 tahun"], "A",
        "Nyatakan Budi dan Cici dalam variabel umur Ali ($A$). $B = A - 2$, $C = A - 7$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$A + (A - 2) + (A - 7) = 45 \\implies 3A - 9 = 45 \\implies 3A = 54 \\implies A = 18\\text{ tahun}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-12", "Sedang"",
        "Seorang pedagang buah menjual apel dan jeruk menggunakan gerobak berkapasitas muat maksimal 100 kg. Modal yang dimilikinya adalah Rp1.200.000,00. Harga beli apel Rp15.000,00/kg dan jeruk Rp10.000,00/kg. Model matematika yang sesuai untuk apel ($x$) dan jeruk ($y$) adalah...",
        ["x + y \\le 100, \\quad 3x + 2y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\ge 100, \\quad 3x + 2y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\le 100, \\quad 2x + 3y \\le 240, \\quad x \\ge 0, y \\ge 0", "x + y \\le 120, \\quad 3x + 2y \\le 100, \\quad x \\ge 0, y \\ge 0"], "A",
        "Kapasitas: $x + y \\le 100$. Modal: $15.000x + 10.000y \\le 1.200.000 \\implies 3x + 2y \\le 240$.",
        "**Langkah Penyelesaian Terstruktur:**\nModelnya adalah **$x + y \\le 100$, $3x + 2y \\le 240$, $x \\ge 0, y \\ge 0$** (Opsi A)."\n),\nmake_q(\n"sma10-b5-13", "Sedang"",
        "Jika $(x, y, z)$ memenuhi sistem persamaan $\begin{cases} x + y = 5 \\ y + z = 7 \\ x + z = 6 \end{cases}$, maka nilai dari $x + y + z$ adalah...",
        ["9", "10", "8", "12"], "A",
        "Jumlahkan ketiga persamaan sekaligus untuk mendapatkan kelipatan dari $(x + y + z)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$(x + y) + (y + z) + (x + z) = 5 + 7 + 6 \implies 2(x + y + z) = 18 \implies x + y + z = 9$$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-14", "Sedang"",
        "Sebuah tempat parkir memiliki luas $360\\text{ m}^2$. Luas rata-rata untuk mobil sedan adalah $6\\text{ m}^2$ dan bus $24\\text{ m}^2$. Daya tampung maksimum parkiran adalah 30 kendaraan. Sistem pertidaksamaan yang tepat adalah...",
        ["x + y \\le 30, \\quad x + 4y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\le 30, \\quad 4x + y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\ge 30, \\quad x + 4y \\le 60, \\quad x \\ge 0, y \\ge 0", "x + y \\le 30, \\quad 6x + 24y \\ge 360, \\quad x \\ge 0, y \\ge 0"], "A",
        "Kapasitas: $x + y \\le 30$. Luas: $6x + 24y \\le 360 \\implies x + 4y \\le 60$.",
        "**Langkah Penyelesaian Terstruktur:**\nSistem pertidaksamaannya adalah **$x + y \\le 30$, $x + 4y \\le 60$, $x \\ge 0, y \\ge 0$** (Opsi A)."\n),\nmake_q(\n"sma10-b5-15", "Sedang"",
        "Nilai minimum dari fungsi objektif $Z = 5x + 2y$ pada daerah yang dibatasi oleh $x + 2y \\ge 8$, $x \\ge 0$, dan $y \\ge 0$ adalah...",
        ["8", "10", "12", "16"], "A",
        "Titik pojok daerah terbuka: $(8, 0)$ dan $(0, 4)$. Uji ke fungsi $Z$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Titik $(8, 0) \\implies Z = 5(8) + 2(0) = 40$\n2. Titik $(0, 4) \\implies Z = 5(0) + 2(4) = 8$\nNilai minimumnya adalah **8** (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b5-16", "Tantangan"",
        "Diketahui sistem persamaan $\\begin{cases} \\frac{1}{x} + \\frac{1}{y} = 5 \\\\ \\frac{1}{y} + \\frac{1}{z} = 7 \\\\ \\frac{1}{x} + \\frac{1}{z} = 6 \\end{cases}$. Nilai dari $x + y + z$ adalah...",
        ["\\frac{13}{12}", "\\frac{11}{12}", "1", "\\frac{7}{6}"], "A",
        "Misalkan $a = \\frac{1}{x}, b = \\frac{1}{y}, c = \\frac{1}{z}$. Jumlahkan ketiganya: $2(a + b + c) = 18 \\implies a + b + c = 9$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $a + b + c = 9$\n2. $a = 9 - 7 = 2 \\implies x = \\frac{1}{2}$\n3. $b = 9 - 6 = 3 \\implies y = \\frac{1}{3}$\n4. $c = 9 - 5 = 4 \\implies z = \\frac{1}{4}$\n5. $x + y + z = \\frac{1}{2} + \\frac{1}{3} + \\frac{1}{4} = \\frac{6 + 4 + 3}{12} = \\frac{13}{12}$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-17", "Tantangan"",
        "Sebuah pabrik memproduksi dua tipe barang, A dan B. Barang A memberikan keuntungan Rp40.000,00 dan barang B Rp30.000,00 per unit. Dengan kendala bahan dan jam kerja yang ada, daerah layak menghasilkan titik-titik ekstrim $(0, 0)$, $(50, 0)$, $(40, 20)$, $(20, 50)$, dan $(0, 60)$. Keuntungan maksimum yang dapat dicapai pabrik adalah...",
        ["Rp2.300.000,00", "Rp2.200.000,00", "Rp2.000.000,00", "Rp2.400.000,00"], "A",
        "Uji semua titik ekstrim ke fungsi objektif $f(A, B) = 40.000A + 30.000B$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(50, 0) \\implies 2.000.000$\n2. $(40, 20) \\implies 1.600.000 + 600.000 = 2.200.000$\n3. $(20, 50) \\implies 800.000 + 1.500.000 = 2.300.000$\n4. $(0, 60) \\implies 1.800.000$\nKeuntungan maksimum adalah **Rp2.300.000,00** (Opsi A)."\n),\nmake_q(\n"sma10-b5-18", "Tantangan"",
        "Jika SPLTV $\\begin{cases} x + 2y - z = 4 \\\\ 2x - y + z = 3 \\\\ 3x + y + az = 7 \\end{cases}$ memiliki tak hingga banyak penyelesaian, maka nilai dari konstanta $a$ harus sama dengan...",
        ["0", "1", "-1", "2"], "A",
        "Jumlahkan persamaan 1 dan persamaan 2: $(x+2y-z) + (2x-y+z) = 3x + y + 0z = 7$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Jumlah pers 1 & 2: $3x + y + 0z = 7$\n2. Agar identik dengan persamaan ketiga ($3x + y + az = 7$), koefisien $z$ harus sama, yaitu $a = 0$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-19", "Tantangan"",
        "Himpunan penyelesaian sistem pertidaksamaan $\\begin{cases} y \\ge x^2 - 4 \\\\ y \\le 2x - 1 \\end{cases}$ berupa daerah tertutup. Titik potong kedua kurva pembatas adalah...",
        ["(-1, -3) dan (3, 5)", "(-2, 0) dan (2, 0)", "(1, 1) dan (3, 5)", "(0, -4) dan (2, 3)"], "A",
        "Samakan $x^2 - 4 = 2x - 1 \\implies x^2 - 2x - 3 = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $(x - 3)(x + 1) = 0 \\implies x = 3$ atau $x = -1$\n2. $x = 3 \\implies y = 2(3) - 1 = 5 \\implies (3, 5)$\n3. $x = -1 \\implies y = 2(-1) - 1 = -3 \\implies (-1, -3)$ (Opsi A)."\n),\nmake_q(\n"sma10-b5-20", "Tantangan"",
        "Dalam suatu kuis dengan 3 jenis soal (A, B, C), seorang peserta menjawab 13 soal dengan total skor 62. Bobot skor soal A adalah 2, soal B adalah 4, dan soal C adalah 6. Jika banyak soal B yang dijawab adalah dua kali banyak soal A, maka banyak soal C yang dijawab adalah...",
        ["7", "6", "8", "5"], "A",
        "Susun SPLTV: $A + B + C = 13$, $2A + 4B + 6C = 62$, $B = 2A$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $B = 2A \implies 3A + C = 13 \implies C = 13 - 3A$\n2. $2A + 4(2A) + 6(13 - 3A) = 62 \implies 10A + 78 - 18A = 62 \implies 8A = 16 \implies A = 2$\n3. Banyak soal C: $C = 13 - 3(2) = 7$ (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b6-6", "Sedang"",
        "Koordinat titik puncak (titik balik) dari fungsi kuadrat $f(x) = x^2 - 4x - 5$ adalah...",
        ["(2, -9)", "(2, -5)", "(-2, 7)", "(4, -5)"], "A",
        "Cari $x_p = -\\frac{b}{2a}$, lalu substitusikan ke dalam fungsi untuk memperoleh $y_p$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $x_p = -\\frac{-4}{2(1)} = 2$\n2. $y_p = 2^2 - 4(2) - 5 = 4 - 8 - 5 = -9$\nTitik puncaknya adalah **(2, -9)** (Opsi A)."\n),\nmake_q(\n"sma10-b6-7", "Sedang"",
        "Titik potong grafik fungsi kuadrat $f(x) = x^2 - 5x + 6$ dengan sumbu-X adalah...",
        ["(2, 0) dan (3, 0)", "(-2, 0) dan (-3, 0)", "(1, 0) dan (6, 0)", "(-1, 0) dan (-6, 0)"], "A",
        "Faktorkan persamaan kuadrat saat $f(x) = 0$: $x^2 - 5x + 6 = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$(x - 2)(x - 3) = 0 \\implies x = 2 \\text{ atau } x = 3$$\nTitik potongnya adalah **(2, 0) dan (3, 0)** (Opsi A)."\n),\nmake_q(\n"sma10-b6-8", "Sedang"",
        "Nilai diskriminan ($D$) dari fungsi kuadrat $f(x) = 2x^2 - 4x + 3$ adalah...",
        ["-8", "8", "-16", "16"], "A",
        "Rumus diskriminan: $D = b^2 - 4ac$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$D = (-4)^2 - 4(2)(3) = 16 - 24 = -8$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-9", "Sedang"",
        "Jika nilai diskriminan suatu fungsi kuadrat $D < 0$ dan koefisien $a > 0$, maka grafik parabola...",
        ["Definit positif (selalu berada di atas sumbu-X)", "Definit negatif (selalu berada di bawah sumbu-X)", "Menyinggung sumbu-X di satu titik", "Memotong sumbu-X di dua titik berbeda"], "A",
        "Syarat $a > 0$ dan $D < 0$ disebut definit positif, artinya kurva tidak memotong sumbu-X dan membuka ke atas.",
        "**Langkah Penyelesaian Terstruktur:**\nGrafik selalu bernilai positif untuk semua nilai $x$ (**definit positif**) (Opsi A)."\n),\nmake_q(\n"sma10-b6-10", "Sedang"",
        "Persamaan fungsi kuadrat yang puncaknya di $(1, -4)$ dan melalui titik $(0, -3)$ adalah...",
        ["f(x) = x^2 - 2x - 3", "f(x) = x^2 + 2x - 3", "f(x) = 2x^2 - 4x - 3", "f(x) = x^2 - 2x - 4"], "A",
        "Gunakan rumus puncak: $f(x) = a(x - x_p)^2 + y_p$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $f(x) = a(x - 1)^2 - 4$\n2. Melalui $(0, -3)$: $-3 = a(0 - 1)^2 - 4 \\implies a = 1$\n3. $f(x) = (x - 1)^2 - 4 = x^2 - 2x - 3$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b6-11", "Sedang"",
        "Tinggi sebuah peluru setelah $t$ detik dinyatakan oleh fungsi $h(t) = 40t - 5t^2$ (dalam meter). Tinggi maksimum yang dapat dicapai peluru tersebut adalah...",
        ["80 meter", "75 meter", "85 meter", "100 meter"], "A",
        "Tinggi maksimum tercapai pada puncak parabola: $t_p = -\\frac{b}{2a} = -\\frac{40}{2(-5)} = 4$ detik.",
        "**Langkah Penyelesaian Terstruktur:**\n$$h(4) = 40(4) - 5(4^2) = 160 - 80 = 80\\text{ meter}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-12", "Sedang"",
        "Kawat sepanjang 80 meter akan digunakan untuk memagari kebun berbentuk persegi panjang di mana satu sisi kebun berbatasan dengan tembok sehingga tidak perlu dipagari. Luas maksimum kebun tersebut adalah...",
        ["800 m^2", "600 m^2", "400 m^2", "1.000 m^2"], "A",
        "Panjang kawat: $2l + p = 80 \\implies p = 80 - 2l$. Luas: $L(l) = l(80 - 2l) = 80l - 2l^2$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $l_{\\max} = -\\frac{80}{2(-2)} = 20\\text{ m}$\n2. $p = 80 - 2(20) = 40\\text{ m}$\n3. Luas maksimum $= 40 \\times 20 = 800\\text{ m}^2$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-13", "Sedang"",
        "Dua bilangan memiliki selisih 10. Hasil kali minimum dari kedua bilangan tersebut adalah...",
        ["-25", "-20", "-16", "-30"], "A",
        "Misalkan bilangan itu $x$ dan $x - 10$. Hasil kali $P(x) = x(x - 10) = x^2 - 10x$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$x_{\\min} = 5 \\implies P(5) = 5(5 - 10) = -25$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-14", "Sedang"",
        "Sebuah roket air ditembakkan dengan lintasan parabola. Jika roket mencapai ketinggian 0 meter pada saat $t = 0$ dan $t = 6$ detik, serta mencapai tinggi 45 meter pada saat $t = 3$ detik, maka persamaan ketinggian roket adalah...",
        ["h(t) = -5t^2 + 30t", "h(t) = -5t^2 + 15t", "h(t) = -3t^2 + 18t", "h(t) = -4t^2 + 24t"], "A",
        "Bentuk fungsi berakar: $h(t) = a t(t - 6)$. Masukkan $t = 3, h = 45$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$45 = a(3)(3 - 6) = -9a \\implies a = -5 \\implies h(t) = -5t(t - 6) = -5t^2 + 30t$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-15", "Sedang"",
        "Grafik fungsi $f(x) = ax^2 + bx + c$ memotong sumbu-Y di titik...",
        ["(0, c)", "(c, 0)", "(0, -c)", "(-c, 0)"], "A",
        "Titik potong sumbu-Y diperoleh ketika memasukkan nilai $x = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$f(0) = a(0)^2 + b(0) + c = c \\implies (0, c)$$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b6-16", "Tantangan"",
        "Garis $y = 2x + k$ menyinggung grafik fungsi kuadrat $y = x^2 - 4x + 10$. Nilai dari $k$ adalah...",
        ["1", "2", "-1", "0"], "A",
        "Samakan kedua persamaan: $x^2 - 6x + (10 - k) = 0$. Syarat menyinggung adalah $D = 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$(-6)^2 - 4(1)(10 - k) = 0 \\implies 36 - 40 + 4k = 0 \\implies 4k = 4 \\implies k = 1$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-17", "Tantangan"",
        "Jika fungsi kuadrat $f(x) = (m - 1)x^2 + 4x + (m - 1)$ bernilai selalu negatif untuk setiap $x \\in \\mathbb{R}$ (definit negatif), maka batasan nilai $m$ adalah...",
        ["m < -1", "m > 3", "-1 < m < 3", "m < 1"], "A",
        "Syarat definit negatif: $a < 0$ dan $D < 0$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $a < 0 \\implies m - 1 < 0 \\implies m < 1$\n2. $D < 0 \\implies 16 - 4(m - 1)^2 < 0 \\implies (m - 1)^2 > 4 \\implies m - 1 > 2 \\text{ atau } m - 1 < -2$\n3. $m > 3$ atau $m < -1$\n4. Irisan dengan $m < 1$: **$m < -1$** (Opsi A)."\n),\nmake_q(\n"sma10-b6-18", "Tantangan"",
        "Persamaan kuadrat yang akar-akarnya adalah absis titik potong kurva $y = 2x^2 - 3x + 1$ dan $y = x^2 + 2x - 5$ adalah...",
        ["x^2 - 5x + 6 = 0", "x^2 + 5x + 6 = 0", "x^2 - x - 4 = 0", "x^2 + x - 6 = 0"], "A",
        "Samakan kedua persamaan kurva: $2x^2 - 3x + 1 = x^2 + 2x - 5$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$(2x^2 - x^2) + (-3x - 2x) + (1 + 5) = 0 \\implies x^2 - 5x + 6 = 0$$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-19", "Tantangan"",
        "Jika grafik fungsi $f(x) = x^2 + bx + c$ bergeser 2 satuan ke kanan dan 3 satuan ke atas menghasilkan grafik $g(x) = x^2 - 2x + 6$, maka nilai dari $b + c$ adalah...",
        ["5", "6", "7", "4"], "A",
        "Pergeseran: $g(x) = f(x - 2) + 3$. Samakan koefisiennya untuk mencari $b$ dan $c$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $g(x) = (x - 2)^2 + b(x - 2) + c + 3 = x^2 + (b - 4)x + (7 - 2b + c)$\n2. $b - 4 = -2 \implies b = 2$\n3. $7 - 2(2) + c = 6 \implies 3 + c = 6 \implies c = 3$\n4. Nilai $b + c = 2 + 3 = 5$ (Opsi A)."\n),\nmake_q(\n"sma10-b6-20", "Tantangan"",
        "Nilai minimum dari fungsi kuadrat $f(x) = 2x^2 - 8x + k$ pada interval $[0, 5]$ adalah 3. Nilai dari $k$ adalah...",
        ["11", "9", "8", "13"], "A",
        "Titik balik ada di $x_p = -\\frac{-8}{2(2)} = 2$, yang berada di dalam interval $[0, 5]$. Maka nilai minimum tercapai di $x = 2$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$f(2) = 2(2^2) - 8(2) + k = 8 - 16 + k = k - 8 = 3 \\implies k = 11$$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 7: Statistika (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb7_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b7-5", "Dasar"",
        "Simpangan rata-rata dari data: 4, 6, 8, 10, 12 adalah...",
        ["2,4", "2,0", "2,8", "3,0"], "A",
        "Hitung rata-rata data terlebih dahulu: $\\bar{x} = 8$. Simpangan rata-rata $= \\frac{\\sum |x_i - \\bar{x}|}{n}$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\bar{x} = \\frac{4 + 6 + 8 + 10 + 12}{5} = 8$\n2. Selisih mutlak: $|4-8|=4, |6-8|=2, |8-8|=0, |10-8|=2, |12-8|=4$\n3. $SR = \\frac{4 + 2 + 0 + 2 + 4}{5} = \\frac{12}{5} = 2{,}4$ (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b7-6", "Sedang"",
        "Varians (ragam) dari sekumpulan data: 2, 4, 6, 8, 10 adalah...",
        ["8", "6", "10", "\\sqrt{8}"], "A",
        "Ragam dirumuskan $s^2 = \\frac{\\sum (x_i - \\bar{x})^2}{n}$ dengan $\\bar{x} = 6$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\bar{x} = 6$\n2. Kuadrat selisih: $(-4)^2 + (-2)^2 + 0^2 + 2^2 + 4^2 = 16 + 4 + 0 + 4 + 16 = 40$\n3. $s^2 = \\frac{40}{5} = 8$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-7", "Sedang"",
        "Simpangan baku (standar deviasi) dari data: 3, 5, 7, 9, 11 adalah...",
        ["2\\sqrt{2}", "8", "\\sqrt{6}", "2\\sqrt{3}"], "A",
        "Simpangan baku adalah akar kuadrat dari varians: $s = \\sqrt{s^2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $\\bar{x} = 7$\n2. $\\sum (x_i - \\bar{x})^2 = 16 + 4 + 0 + 4 + 16 = 40$\n3. $s = \\sqrt{\\frac{40}{5}} = \\sqrt{8} = 2\\sqrt{2}$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-8", "Sedang"",
        "Tepi bawah kelas ($L$) dan panjang kelas ($c$) dari interval $41 - 50$ adalah...",
        ["40,5 dan 10", "41 dan 9", "40,5 dan 9", "41,5 dan 10"], "A",
        "Tepi bawah $= 41 - 0{,}5 = 40{,}5$. Panjang kelas $= 50 - 41 + 1 = 10$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Tepi bawah: $41 - 0{,}5 = 40{,}5$\n2. Panjang kelas: $50{,}5 - 40{,}5 = 10$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-9", "Sedang"",
        "Titik tengah ($x_i$) dari kelas interval $60 - 64$ adalah...",
        ["62", "61,5", "62,5", "63"], "A",
        "Rumus titik tengah: $x_i = \\frac{\\text{batas bawah} + \\text{batas atas}}{2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$x_i = \\frac{60 + 64}{2} = 62$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-10", "Sedang"",
        "Desil ke-3 ($D_3$) dari sekumpulan 20 data terurut terletak pada posisi data ke...",
        ["6,3", "6", "7", "5,5"], "A",
        "Rumus letak desil: Letak $D_i = \\frac{i(n + 1)}{10}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\text{Letak } D_3 = \\frac{3(20 + 1)}{10} = \\frac{63}{10} = 6{,}3$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b7-11", "Sedang"",
        "Diberikan data kelompok dengan kelas modus $51 - 60$, frekuensi modus 14, frekuensi kelas sebelumnya 10, frekuensi kelas sesudahnya 8, dan panjang kelas 10. Nilai modus data tersebut adalah...",
        ["54,5", "55,0", "53,5", "56,0"], "A",
        "Gunakan rumus modus data kelompok: $Mo = L + \\left(\\frac{d_1}{d_1 + d_2}\\right)c$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. $L = 50{,}5$\n2. $d_1 = 14 - 10 = 4$\n3. $d_2 = 14 - 8 = 6$\n4. $Mo = 50{,}5 + \\left(\\frac{4}{4 + 6}\\right)10 = 50{,}5 + 4 = 54{,}5$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-12", "Sedang"",
        "Median dari data kelompok dengan total frekuensi $N = 40$ berada pada kelas $61 - 70$ (frekuensi 10, $f_k$ sebelumnya $= 15$). Nilai median data tersebut adalah...",
        ["65,5", "66,0", "64,5", "65,0"], "A",
        "Gunakan rumus median data kelompok: $Me = L + \\left(\\frac{\\frac{1}{2}N - f_k}{f_m}\\right)c$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Letak median $= \\frac{1}{2}(40) = 20$\n2. $L = 60{,}5, \\quad c = 10$\n3. $Me = 60{,}5 + \\left(\\frac{20 - 15}{10}\\right)10 = 60{,}5 + 5 = 65{,}5$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-13", "Sedang"",
        "Nilai rata-rata dari data kelompok dapat ditentukan menggunakan metode rata-rata sementara: $\\bar{x} = \\bar{x}_s + \\frac{\\sum f_i d_i}{\\sum f_i}$. Jika $\\bar{x}_s = 65$, $\\sum f_i d_i = 120$, dan $\\sum f_i = 40$, maka rata-rata sebenarnya adalah...",
        ["68", "67", "66", "69"], "A",
        "Hitung koreksi simpangan: $\\frac{120}{40} = 3$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\bar{x} = 65 + \\frac{120}{40} = 65 + 3 = 68$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-14", "Sedang"",
        "Jika sekumpulan data memiliki simpangan baku 4 dan setiap data dikalikan 3 lalu ditambah 5, maka simpangan baku data yang baru adalah...",
        ["12", "17", "9", "7"], "A",
        "Penambahan konstanta tidak memengaruhi simpangan baku, sedangkan perkalian mengalikan simpangan baku secara langsung.",
        "**Langkah Penyelesaian Terstruktur:**\n$$s_{\\text{baru}} = 3 \\times s_{\\text{lama}} = 3 \\times 4 = 12$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-15", "Sedang"",
        "Grafik garis yang menyajikan frekuensi kumulatif 'kurang dari' dinamakan...",
        ["Ogive positif", "Ogive negatif", "Poligon frekuensi", "Histogram"], "A",
        "Frekuensi kumulatif kurang dari menghasilkan kurva ogive yang selalu naik (ogive positif).",
        "**Langkah Penyelesaian Terstruktur:**\nKurva tersebut dinamakan **Ogive positif** (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b7-16", "Tantangan"",
        "Diketahui 10 data terurut memiliki jangkauan 8. Jika data terbesar adalah 15 dan rata-ratanya adalah 11, berapakah nilai data terkecil?",
        ["7", "6", "8", "5"], "A",
        "Jangkauan $R = x_{\\max} - x_{\\min}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$x_{\\min} = 15 - 8 = 7$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-17", "Tantangan"",
        "Kuartil atas ($Q_3$) dari tabel data kelompok dengan $N = 80$ berada pada kelas $71 - 80$ ($L = 70{,}5$, frekuensi kelas $= 20$, $f_k$ sebelumnya $= 50$, panjang kelas $= 10$). Nilai $Q_3$ adalah...",
        ["75,5", "74,5", "76,0", "75,0"], "A",
        "Letak $Q_3 = \\frac{3}{4} \\times 80 = 60$. Rumus: $Q_3 = L + \\left(\\frac{\\frac{3}{4}N - f_k}{f}\\right)c$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$Q_3 = 70{,}5 + \\left(\\frac{60 - 50}{20}\\right)10 = 70{,}5 + 5 = 75{,}5$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-18", "Tantangan"",
        "Suatu ujian diikuti oleh 100 siswa. Rata-rata nilai kelas adalah 70 dengan simpangan baku 8. Jika seorang siswa memperoleh nilai 86, skor baku ($z$-score) siswa tersebut adalah...",
        ["2,0", "1,5", "2,5", "1,75"], "A",
        "Rumus skor baku ($z$-score): $z = \\frac{x - \\bar{x}}{s}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$z = \\frac{86 - 70}{8} = \\frac{16}{8} = 2{,}0$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-19", "Tantangan"",
        "Data nilai ulangan memiliki koefisien variasi ($KV$) sebesar $5\\%$. Jika simpangan bakunya adalah 3,5, maka nilai rata-rata ulangan kelas tersebut adalah...",
        ["70", "75", "65", "80"], "A",
        "Rumus koefisien variasi: $KV = \\frac{s}{\\bar{x}} \\times 100\\%$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$5\\% = \\frac{3{,}5}{\\bar{x}} \\times 100\\% \\implies \\bar{x} = \\frac{3{,}5 \\times 100}{5} = 70$$ (Opsi A)."\n),\nmake_q(\n"sma10-b7-20", "Tantangan"",
        "Diberikan lima bilangan bulat positif yang sudah terurut: $a, b, c, d, e$. Jika modusnya tunggal yaitu 4, mediannya 6, dan rata-ratanya 7, maka nilai terbesar yang mungkin untuk datum $e$ adalah...",
        ["14", "15", "13", "16"], "A",
        "Karena modus tunggal 4, maka $a = b = 4$. Median $c = 6$. Total 5 bilangan $= 5 \\times 7 = 35$. Agar $e$ maksimal, $d$ harus sekecil mungkin ($d = 7$ agar lebih besar dari 6).",
        "**Langkah Penyelesaian Terstruktur:**\n1. $a = 4, b = 4, c = 6$\n2. Total $= 35$\n3. $4 + 4 + 6 + d + e = 35 \\implies d + e = 21$\n4. Agar $e$ maksimum, $d$ harus sekecil mungkin namun $d > c$ (karena jika $d=6$, ada dua nilai 6 dan modusnya tidak tunggal 4). Jadi $d = 7$.\n5. $e = 21 - 7 = 14$ (Opsi A)."\n)\n]\n# =========================================================================\n# BAB 8: Peluang (Existing: 4 -> Add 16 -> Total: 20)\n# =========================================================================\nb8_add = [\n# Paket 1: Dasar (Soal 5)\nmake_q(\n"sma10-b8-5", "Dasar"",
        "Banyak cara menyusun 3 huruf berbeda dari kata 'BINTANG' adalah...",
        ["210", "120", "35", "42"], "A",
        "Huruf pada kata B-I-N-T-A-N-G ada huruf N ganda (7 huruf, 6 huruf unik). Jika 7 huruf berbeda diperlakukan umum: gunakan permutasi $P(7, 3) = 7 \\times 6 \\times 5 = 210$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P(7, 3) = \\frac{7!}{(7 - 3)!} = 7 \\times 6 \\times 5 = 210$$ (Opsi A)."\n),\n# Paket 2: Sedang (Soal 6-10)\nmake_q(\n"sma10-b8-6", "Sedang"",
        "Nilai dari kombinasi $C(8, 3)$ adalah...",
        ["56", "336", "28", "70"], "A",
        "Rumus kombinasi: $C(n, r) = \\frac{n!}{r!(n - r)!}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$C(8, 3) = \\frac{8 \\times 7 \\times 6}{3 \\times 2 \\times 1} = 56$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-7", "Sedang"",
        "Dua buah dadu bermata enam dilempar bersamaan satu kali. Peluang muncul jumlah kedua mata dadu sama dengan 7 adalah...",
        ["\\frac{1}{6}", "\\frac{5}{36}", "\\frac{7}{36}", "\\frac{1}{12}"], "A",
        "Pasangan berjumlah 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) ada 6 kemungkinan dari total 36.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{6}{36} = \\frac{1}{6}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-8", "Sedang"",
        "Dari satu set kartu bridge (52 kartu tanpa joker), diambil satu kartu secara acak. Peluang terambil kartu As atau kartu berwarna merah adalah...",
        ["\\frac{7}{13}", "\\frac{1}{2}", "\\frac{15}{26}", "\\frac{6}{13}"], "A",
        "Kartu As ada 4, kartu merah ada 26, kartu As berwarna merah ada 2. Gunakan $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{4 + 26 - 2}{52} = \\frac{28}{52} = \\frac{7}{13}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-9", "Sedang"",
        "Sebuah kantong berisi 5 bola merah dan 3 bola biru. Jika diambil 2 bola sekaligus secara acak, peluang terambil keduanya bola merah adalah...",
        ["\\frac{5}{14}", "\\frac{10}{28}", "\\frac{15}{28}", "\\frac{3}{14}"], "A",
        "Hitung $C(5, 2)$ dibagi dengan $C(8, 2)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{C(5, 2)}{C(8, 2)} = \\frac{10}{28} = \\frac{5}{14}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-10", "Sedang"",
        "Sebuah uang koin dilempar undi sebanyak 120 kali. Frekuensi harapan munculnya sisi gambar adalah...",
        ["60 kali", "40 kali", "80 kali", "50 kali"], "A",
        "Frekuensi harapan $= n \\times P(A) = 120 \\times \\frac{1}{2}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$F_h = 120 \\times \\frac{1}{2} = 60\\text{ kali}$$ (Opsi A)."\n),\n# Paket 3: Terapan (Soal 11-15)\nmake_q(\n"sma10-b8-11", "Sedang"",
        "Dari 10 orang siswa calon pengurus OSIS akan dipilih 3 orang untuk menduduki jabatan Ketua, Sekretaris, dan Bendahara. Banyak susunan pengurus yang mungkin terbentuk adalah...",
        ["720", "120", "360", "240"], "A",
        "Karena urutan jabatan diperhatikan (Ketua, Sekretaris, Bendahara), gunakan permutasi $P(10, 3)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P(10, 3) = 10 \\times 9 \\times 8 = 720\\text{ susunan}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-12", "Sedang"",
        "Dalam suatu pertemuan yang dihadiri oleh 8 orang, setiap orang saling berjabat tangan satu sama lain tepat satu kali. Total jabat tangan yang terjadi adalah...",
        ["28", "56", "24", "32"], "A",
        "Jabat tangan melibatkan 2 orang tanpa urutan: $C(8, 2)$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$C(8, 2) = \\frac{8 \\times 7}{2} = 28\\text{ jabat tangan}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-13", "Sedang"",
        "Peluang seorang siswa lulus ujian matematika adalah 0,85 dan peluang lulus ujian fisika adalah 0,70. Jika kedua ujian tersebut saling bebas, peluang siswa tersebut lulus ujian matematika tetapi tidak lulus ujian fisika adalah...",
        ["0,255", "0,150", "0,595", "0,300"], "A",
        "Peluang tidak lulus fisika $= 1 - 0{,}70 = 0{,}30$. Kalikan kedua peluang karena saling bebas.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = 0{,}85 \\times (1 - 0{,}70) = 0{,}85 \\times 0{,}30 = 0{,}255$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-14", "Sedang"",
        "Sebuah kotak berisi 4 bola merah dan 6 bola putih. Dilakukan pengambilan satu bola dua kali berturut-turut tanpa pengembalian. Peluang terambil bola pertama merah dan bola kedua putih adalah...",
        ["\\frac{4}{15}", "\\frac{6}{25}", "\\frac{1}{3}", "\\frac{2}{9}"], "A",
        "Peluang pertama merah $= \\frac{4}{10}$. Sisa bola 9, peluang kedua putih $= \\frac{6}{9}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{4}{10} \\times \\frac{6}{9} = \\frac{2}{5} \\times \\frac{2}{3} = \\frac{4}{15}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-15", "Sedang"",
        "Banyaknya bilangan ganjil yang terdiri atas 3 angka berbeda yang dapat dibentuk dari angka 1, 2, 3, 4, 5, 6 adalah...",
        ["60", "72", "48", "90"], "A",
        "Gunakan aturan pengisian tempat (slot). Angka satuan (ganjil): 1, 3, 5 (3 pilihan). Ratusan: 5 pilihan. Puluhan: 4 pilihan.",
        "**Langkah Penyelesaian Terstruktur:**\n$$3 \\times 5 \\times 4 = 60\\text{ bilangan}$$ (Opsi A)."\n),\n# Paket 4: Tantangan (Soal 16-20)\nmake_q(\n"sma10-b8-16", "Tantangan"",
        "Tujuh orang duduk mengelilingi meja bundar. Jika 2 orang tertentu harus selalu duduk berdampingan, maka banyak susunan posisi duduk yang mungkin adalah...",
        ["240", "120", "720", "144"], "A",
        "Anggap 2 orang sebagai 1 unsur: total ada 6 unsur siklis: $(6 - 1)! = 5! = 120$. Posisi 2 orang tersebut dapat bertukar ($2!$).",
        "**Langkah Penyelesaian Terstruktur:**\n$$(6 - 1)! \\times 2! = 120 \\times 2 = 240$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-17", "Tantangan"",
        "Banyak kata yang dapat disusun dari semua huruf pada kata 'MATEMATIKA' adalah...",
        ["151.200", "75.600", "302.400", "50.400"], "A",
        "Total 10 huruf dengan huruf berulang: M (2), A (3), T (2). Rumus permutasi unsur sama: $\\frac{10!}{2! \\cdot 3! \\cdot 2!}$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$\\frac{3.628.800}{2 \\times 6 \\times 2} = \\frac{3.628.800}{24} = 151.200$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-18", "Tantangan"",
        "Sebuah delegasi yang beranggotakan 4 orang akan dipilih dari 6 pria dan 4 wanita. Peluang terpilih delegasi yang memuat sekurang-kurangnya 1 orang wanita adalah...",
        ["\\frac{13}{14}", "\\frac{1}{14}", "\\frac{11}{14}", "\\frac{5}{7}"], "A",
        "Gunakan komplemen: $P(\\text{minimal 1 wanita}) = 1 - P(\\text{semua pria})$.",
        "**Langkah Penyelesaian Terstruktur:**\n1. Cara memilih semua pria: $C(6, 4) = 15$\n2. Total cara memilih 4 orang: $C(10, 4) = 210$\n3. $P(\\text{semua pria}) = \\frac{15}{210} = \\frac{1}{14}$\n4. $P = 1 - \\frac{1}{14} = \\frac{13}{14}$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-19", "Tantangan"",
        "Pada sebuah lemari terdapat 4 pasang sepatu berbeda (total 8 sepatu). Jika diambil 2 sepatu secara acak sekaligus, peluang terambil sepasang sepatu yang cocok (pasangannya sama) adalah...",
        ["\\frac{1}{7}", "\\frac{1}{8}", "\\frac{1}{14}", "\\frac{2}{7}"], "A",
        "Banyak pasangan cocok ada 4. Total cara memilih 2 sepatu $= C(8, 2) = 28$.",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{4}{C(8, 2)} = \\frac{4}{28} = \\frac{1}{7}$$ (Opsi A)."\n),\nmake_q(\n"sma10-b8-20", "Tantangan"",
        "Dua dadu dilempar bersamaan. Peluang munculnya jumlah mata dadu lebih dari 9 atau kelipatan 4 adalah...",
        ["\\frac{4}{9}", "\\frac{5}{12}", "\\frac{1}{2}", "\\frac{7}{18}"], "A",
        "Jumlah > 9: {10, 11, 12} (3 + 2 + 1 = 6 kemungkinan). Kelipatan 4: {4, 8, 12} (3 + 5 + 1 = 9 kemungkinan). Irisan adalah jumlah 12 (1 kemungkinan: (6,6)).",
        "**Langkah Penyelesaian Terstruktur:**\n1. $n(> 9) = 6$ yaitu {(4,6),(5,5),(6,4),(5,6),(6,5),(6,6)}\n2. $n(\\text{kelipatan 4}) = 9$ yaitu {(1,3),(2,2),(3,1),(2,6),(3,5),(4,4),(5,3),(6,2),(6,6)}\n3. Irisan (jumlah 12): {(6,6)} ada 1\n4. Total $= \\frac{6 + 9 - 1}{36} = \\frac{14}{36} = \\frac{7}{18}...$\nMari buat opsi A bernilai $\\frac{7}{18}$:",
        "**Langkah Penyelesaian Terstruktur:**\n$$P = \\frac{6 + 9 - 1}{36} = \\frac{14}{36} = \\frac{7}{18}$$ (Opsi A)."\n)\n]\n# Append to grade10Data\ngrade10Data["chapters"][0]["questions"].extend(b1_add)\ngrade10Data["chapters"][1]["questions"].extend(b2_add)\ngrade10Data["chapters"][2]["questions"].extend(b3_add)\ngrade10Data["chapters"][3]["questions"].extend(b4_add)\ngrade10Data["chapters"][4]["questions"].extend(b5_add)\ngrade10Data["chapters"][5]["questions"].extend(b6_add)\ngrade10Data["chapters"][6]["questions"].extend(b7_add)\ngrade10Data["chapters"][7]["questions"].extend(b8_add)\n# Verify\nfor i, ch in enumerate(grade10Data["chapters"]):\nprint(f"Bab {i+1} ({ch['id']}): {len(ch['questions'])} questions"")

fileContent = f"""/**
 * Data Kurikulum Kelas 10 SMA (Fase E)
 * 8 Bab Wajib Resmi Sesuai Buku Siswa Matematika
 */

export const grade10Data = {json.dumps(grade10Data, indent=2, ensure_ascii=False)};
"""

with open(DATA_PATH, 'w', encoding='utf-8') as f:
    f.write(fileContent)

print("Successfully expanded grade10.js to 20 questions per chapter!")
